# **CA3-Part2, LLMs Spring 2025**

- **Name: Mohammad Amanlou**
- **Student ID: 810100084**

---
#### Your submission should be named using the following format: `CA3-Part2_LASTNAME_STUDENTID.ipynb`.

---

##### *How to do this problem set:*

- Some questions require writing Python code and computing results, and the rest of them have written answers. For coding problems, you will have to fill out all code blocks under each `Completion` section.

- For text-based answers, you should replace the text that says `WRITE YOUR ANSWER HERE` with your actual answer, or you can look for `Report` and `Question` blocks.

- There is no penalty for using AI assistance on this homework as long as you fully disclose it in the final cell of this notebook (this includes storing any prompts that you feed to large language models). That said, anyone caught using AI assistance without proper disclosure will receive a zero on the assignment (we have several automatic tools to detect such cases). We're literally allowing you to use it with no limitations, so there is no reason to lie!

---

##### *Academic honesty*

- We will audit the Colab notebooks from a set number of students, chosen at random. The audits will check that the code you wrote actually generates the answers in your notebook. If you turn in correct answers on your notebook without code that actually generates those answers, we will consider this a serious case of cheating.

- We will also run automatic checks of Colab notebooks for plagiarism. Copying code from others is also considered a serious case of cheating.

---

If you have any further questions or concerns, contact the TAs via email or Telegram.

# RAG (50 points)

If you have any further questions or concerns, contact the TA via email (pouya.sadeghi@ut.ac.ir) or telegram.

## Install Requirements

In [ ]:
!pip install -q --no-deps langchain langchain_community langchain_huggingface huggingface_hub
!pip install -q --no-deps sentence_transformers tiktoken lark datasets
!pip install --upgrade numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 36.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 8.3 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)
Collecting numpy
  Downloading numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.0 MB/s eta 0:00:00
Downloading numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 65.3 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-community 0.3.24 requires dataclasses-json<0.7,>=0.5.7, which is not installed.
langchain-community 0.3.24 requires httpx-sse<1.0.0,>=0.4.0, which is not installed.
langchain-community 0.3.24 requires pydantic-settings<3.0.0,>=2.4.0, which is not installed.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.5 which is incompatible.
Successfully installed numpy-2.2.5

In [ ]:
# To determine your system's CUDA version, run the following command:
#!nvidia-smi

# Based on your CUDA version, install the appropriate FAISS-GPU package:

# For CUDA 12.x:
!pip install -q faiss-gpu-cu12

# For CUDA 11.x:
# !pip install faiss-gpu-cu11

# If you prefer the CPU-only version of FAISS:
#!pip install -q faiss-cpu

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-community 0.3.24 requires dataclasses-json<0.7,>=0.5.7, which is not installed.
langchain-community 0.3.24 requires httpx-sse<1.0.0,>=0.4.0, which is not installed.
langchain-community 0.3.24 requires pydantic-settings<3.0.0,>=2.4.0, which is not installed.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.

## 1. An Overview of Information Retrieval (IR) and RAG (2 points)

- **Information Retrieval (IR)**: The process of obtaining information system resources relevant to a specific information need from a collection of those resources. Each IR system consists of a collection of documents, a set of queries, and a retrieval function that ranks the documents based on their relevance to the query.
- **Retrieval-Augmented Generation (RAG)**: A model that combines the strengths of retrieval-based and generation-based approaches. It retrieves relevant documents from a large corpus and uses them to generate a response to a query. RAG is particularly useful for tasks where the answer is not explicitly present in the training data but can be inferred from related documents.
- **RAG Architecture**: The RAG architecture consists of two main components:
  - **Retriever**: This component retrieves relevant documents from a large corpus based on the input query. It can be implemented using various retrieval methods, such as BM25 or dense retrieval.
  - **Generator**: This component generates a response based on the retrieved documents and the input query. It can be implemented using transformer-based models.
  
In this computer assignment, you will implement a RAG pipeline using the LangChain framework. You will use two different retrievers: TF-IDF and dense retriever.

#### Question 1: (2 points)
1. Why do we need to use RAG?
2. What is LangChain and how does it help in building RAG pipelines?
<!-- 2. What are the advantages of RAG over generation methods? -->
<!-- 3. What is the difference between dense and sparse retrievers? -->

We need to use Retrieval-Augmented Generation (RAG) because:

* It combines **retrieval** of relevant external documents with **generation** of natural language responses, allowing the model to answer questions that require up-to-date or detailed information not explicitly present in its training data.
* RAG improves accuracy and knowledge coverage by accessing a large external corpus, making it better at answering complex queries or rare facts.
* It reduces the need for very large and expensive-to-train models by augmenting generation with retrieved context.
* RAG models are more flexible and can adapt to new information without retraining by simply updating the retrieval database.

**LangChain** is an open-source framework designed to help developers build applications that combine Large Language Models (LLMs) with other data sources and tools in a modular and scalable way.

**How LangChain helps in building RAG pipelines:**

* **Modular Components:** LangChain provides easy-to-use modules for retrievers, prompt templates, chains, and integrations with various LLMs and data stores.
* **Simplifies Integration:** It allows seamless integration of retrievers (like TF-IDF or dense vector search) with language models, enabling efficient retrieval-augmented generation workflows.
* **Prompt Management:** LangChain manages prompt templates and message flows, making it easier to construct complex conversational or generative prompts using retrieved documents as context.
* **Pipeline Orchestration:** It supports chaining and composing multiple steps, such as retrieval followed by generation, with clear data flow and input/output handling.
* **Extensibility:** LangChain supports various backends for retrieval, embeddings, and generation, allowing customization for specific RAG use cases.

## 2. An Overview of LangChain (12 points + 2)

In this overview, we will provide a step-by-step guide on how to construct a basic application using LangChain. To learn more about this framework, check its [tutorial](https://python.langchain.com/docs/tutorials/) which is available for different releases!

### 2.1 Lets load our model (4 points)

#### Question 2: (2 points)

1. Explain how different parameters, such as `temperature`, `max_length`, `top_p`, `top_k`, and `repetition_penalty`, affect the generation process in a language model.

**Temperature** controls the randomness of the output. Lower values make the text more focused and deterministic, while higher values allow for more creativity but can sometimes lead to less coherent responses.

**Max length** (or `max_new_tokens`) sets a limit on the number of tokens the model can generate, ensuring that the output doesn’t become overly long.

**Top-p** (nucleus sampling) determines the cumulative probability of token selection. The model only considers tokens within a certain probability range, like 90% for `top_p=0.9`, balancing randomness and coherence.

**Top-k** restricts the model to choosing from the top-k most likely tokens at each step. For example, `top_k=50` lets the model pick from the 50 most probable options. Smaller values reduce randomness, while larger values increase it.

**Repetition penalty** discourages the model from repeating words or phrases excessively by penalizing tokens it has already generated. This helps avoid repetitive or looping text.

#### Completion 1: (2 points)

Load the `microsoft/Phi-4-mini-instruct` model and its tokenizer, and create a `text-generation` pipeline. Use the LangChain framework to integrate the model into your application. You should configure the pipeline with appropriate parameters, such as *max_new_tokens*, *temperature*, *top_p*, *top_k*, and *repetition_penalty*.

In [ ]:
!huggingface-cli login --token {"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"}

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
The token `UT` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `UT`

In [ ]:
!pip uninstall numpy scipy scikit-learn -y
!pip install numpy scipy scikit-learn

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: scipy 1.15.3
Uninstalling scipy-1.15.3:
  Successfully uninstalled scipy-1.15.3
Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Collecting numpy
  Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting scipy
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 6.1 MB/s eta 0:00:00
Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)
Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 16.0 MB/s eta 0:00:00
Downloading scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 51.5 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-community 0.3.24 requires dataclasses-json<0.7,>=0.5.7, which is not installed.
langchain-community 0.3.24 requires httpx-sse<1.0.0,>=0.4.0, which is not installed.
langchain-community 0.3.24 requires pydantic-settings<3.0.0,>=2.4.0, which is not installed.
faiss-gpu-cu12 1.11.0 requires numpy<2, but you have numpy 2.2.5 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.5 which is incompatible.
Successfully installed numpy-2.2.5 scikit-learn-1.6.1 scipy-1.15.3

In [ ]:
from langchain_huggingface.llms import HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import numpy

model_id = "microsoft/Phi-4-mini-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id,
                device_map="cuda",
                torch_dtype="auto",
                trust_remote_code=False)

tokenizer.pad_token = tokenizer.eos_token
pipe = pipeline("text-generation",
                model=model,
                tokenizer=tokenizer,
                max_new_tokens=200,
                top_p = 1,
                top_k = 50,
                temperature=0,
                eos_token_id=tokenizer.eos_token_id)
llm = HuggingFacePipeline(pipeline=pipe)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda

In [ ]:
response = llm.invoke("Who is the president of the United States?")
print(response)

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Who is the president of the United States? The president of the United States is Joe Biden. He assumed office on January 20, 2021, after winning the 2020 presidential election.

### 2.2 Simple Chain (4 points)

#### Completion 2: (2 points)

Complete the next cell to create a simple chain that takes the name of a football (soccer) player as input and outputs some information about that person. To do so:

1. Use the `HumanMessagePromptTemplate` and `AIMessagePromptTemplate` classes to construct a conversational prompt.
2. Use `ChatPromptTemplate` to organize the messages.
3. Pass the prompt into the model you have loaded before.
4. Use `StrOutputParser` to return a plain string.

Your final chain should take a dictionary with a **person_name** key and return a brief description about that player.

In [ ]:
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate
from langchain_core.output_parsers import StrOutputParser

human_message = HumanMessagePromptTemplate.from_template(
    "Tell me some brief information about the football player named {person_name}."
)

prompt = ChatPromptTemplate.from_messages([human_message])

output_parser = StrOutputParser()

class SimpleChain:
    def __init__(self, llm, prompt, output_parser):
        self.llm = llm
        self.prompt = prompt
        self.output_parser = output_parser

    def invoke(self, input_dict):
        messages = self.prompt.format_messages(**input_dict)
        input_text = messages[0].content

        # استفاده از متد invoke بجای __call__
        output = self.llm.invoke(input_text)

        # اگر خروجی رشته است مستقیم پارس کن
        # اگر خروجی دیکشنری یا لیست بود، باید اصلاح شود
        if isinstance(output, str):
            raw_text = output
        elif isinstance(output, list) and isinstance(output[0], dict) and 'generated_text' in output[0]:
            raw_text = output[0]['generated_text']
        else:
            # اگر فرمت خروجی متفاوت است اینجا اصلاح کن
            raw_text = str(output)

        return self.output_parser.parse(raw_text)


simple_chain = SimpleChain(llm=llm, prompt=prompt, output_parser=output_parser)

In [ ]:
answer = simple_chain.invoke({"person_name": "Kylian Mbappé"})
print(answer)

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Tell me some brief information about the football player named Kylian Mbappé. Your response should contain exactly 3 bullet points using the markdown bullet points format, such as: * Bullet point 1. * Kylian Mbappé is a professional French footballer who plays as a forward for Paris Saint-Germain and the French national team.
* He is known for his exceptional speed, dribbling skills, and goal-scoring ability, making him one of the most promising young talents in football.
* Mbappé has won multiple titles with Paris Saint-Germain, including the Ligue 1 championship, and has been a key player in France's success in the UEFA European Championship.

#### Question 3: (2 points)

1. Write about the objectives behind the creation of `HumanMessagePromptTemplate` and `AIMessagePromptTemplate` classes. What they actually do and how should we use them? Write a brief description.

`HumanMessagePromptTemplate` and `AIMessagePromptTemplate` are designed to simplify and organize conversational interactions in artificial intelligence systems. These templates differentiate between human inputs and AI-generated outputs, creating clarity in multi-turn conversations. The `HumanMessagePromptTemplate` is responsible for formatting user inputs, preparing them in a way that is suitable for the AI model to process. On the other hand, the `AIMessagePromptTemplate` handles the formatting of AI-generated responses or system-level messages, ensuring that the outputs remain consistent and coherent. To use these templates, you can utilize `HumanMessagePromptTemplate` to structure human inputs, which may include placeholders for dynamic content, and `AIMessagePromptTemplate` to define the structure and expectations of AI responses. By combining these templates within a `ChatPromptTemplate`, you can design a well-organized and structured multi-turn interaction flow tailored for chat-based models.

### 2.3 JSON Chain (4 points)

#### Completion 3: (1 point)

Now we want to improve the chain to extract data from the model response. Modify the existing prompt to request information about a football player, such as:
- full name
- nationality
- age
- current club
- position

In this chain, you can use `SystemMessagePromptTemplate` as well.
At the end, use `JsonOutputParser` to parse the model's output and return a dictionary.

In [ ]:
from langchain_core.prompts import (
    SystemMessagePromptTemplate,
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    AIMessagePromptTemplate,
)
from langchain_core.output_parsers import JsonOutputParser

system_message = SystemMessagePromptTemplate.from_template(
    "You are a helpful assistant that provides detailed info about football players in JSON format."
)

human_message = HumanMessagePromptTemplate.from_template(
    (
        "Provide the following information about the football player named {player_name}:\n"
        "- full name\n"
        "- nationality\n"
        "- age\n"
        "- current club\n"
        "- position\n\n"
        "Format your response strictly as a JSON object."
    )
)

# Optional: AI message template just for formatting (can be omitted)
ai_message = AIMessagePromptTemplate.from_template("{answer}")

# Build chat prompt with system, human (and AI) messages
prompt = ChatPromptTemplate.from_messages([system_message, human_message])

# Use JsonOutputParser to parse JSON response into dict
output_parser = JsonOutputParser()

class JsonChain:
    def __init__(self, llm, prompt, output_parser):
        self.llm = llm
        self.prompt = prompt
        self.output_parser = output_parser

    def invoke(self, input_dict):
        messages = self.prompt.format_messages(**input_dict)
        input_text = messages[1].content  # human message content (index 1 is human prompt)
        output = self.llm.invoke(input_text)
        return self.output_parser.parse(output)

    def batch(self, input_list):
        results = []
        for input_dict in input_list:
            try:
                result = self.invoke(input_dict)
            except Exception as e:
                result = {"error": str(e), "input": input_dict}
            results.append(result)
        return results

# Instantiate the chain
json_chain = JsonChain(llm=llm, prompt=prompt, output_parser=output_parser)

In [ ]:
json_chain.invoke({"player_name": "Lionel Messi"})

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

{'full_name': 'Lionel Andrés Messi',
 'nationality': 'Argentine',
 'age': 34,
 'current_club': 'Paris Saint-Germain',
 'position': 'Forward'}

In [ ]:
# Batch the requests for multiple
batch_questions = [
  {"player_name": "Lionel Messi"},
  {"player_name": "Cristiano Ronaldo"},
  {"player_name": "Kylian Mbappé"},
  {"player_name": "Neymar"}
]
answers = json_chain.batch(batch_questions)

# Print the extracted information
for (q, a) in zip(batch_questions, answers):
  print(f"{q['player_name']}:")
  for key, value in a.items():
    print(f"  {key}: {value}")
  print()

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Lionel Messi:
  full_name: Lionel Andrés Messi
  nationality: Argentine
  age: 34
  current_club: Paris Saint-Germain
  position: Forward

Cristiano Ronaldo:
  full_name: Cristiano Ronaldo dos Santos Aveiro
  nationality: Portuguese
  age: 37
  current_club: Al Nassr
  position: Forward

Kylian Mbappé:
  full_name: KYLIAN MBAPPE
  nationality: FRENCH
  age: 22
  current_club: PSG
  position: FORWARD

Neymar:
  full_name: Neymar Jr.
  nationality: Brazilian
  age: 32
  current_club: Paris Saint-Germain
  position: Forward

#### Report 1: (1 point)

Explain the challenges you faced in this step. How did you manage to solve them? How could the parameters you used in the text generation pipeline affect the model’s output?

It was one of the most challenging tasks I’ve faced recently. The parser couldn’t automatically separate the output, so I had to do it manually. The bigger issue was that even the slightest extra output, like a stray character or a newline, would cause JSON errors. I had to tweak the prompt repeatedly to ensure the model generated the exact format I needed. Even the smallest mistake could ruin the entire process. It was an exhausting and detail-heavy experience.

#### Question 4: (2 points)

1. How sampling parameters such as *temperature*, *top_p*, and *top_k* can affect our JSON pipeline? Answer the question with respect to the format and content.

Sampling parameters control the randomness and diversity of the model's output. When generating structured data like JSON, even a small mistake—like changing a single character (e.g., a bracket, quote, comma)—can break the JSON format and cause parsing errors.

Temperature: Higher temperature increases randomness, making the model more likely to produce unexpected or malformed JSON syntax.

Top_p and Top_k: These limit the token choices during sampling. If set too loosely, the model might choose tokens that disrupt the strict JSON format (like missing quotes or extra commas).

Because JSON requires strict syntax, we must carefully set these parameters (usually low temperature, moderate to low top_p and top_k) to reduce randomness and ensure the output stays valid and parseable.

### 2.4 (Optional) Tool use: Web search (2 points)

#### Completion 4: (2 points)

Add context about each player by using web search. For this purpose, you need to use a web search tool, and write a function to check the output of the search tool.

In [ ]:
#!pip install --quiet langchain[serpapi]
#!pip install --upgrade langchain
!pip install -U duckduckgo-search

Collecting duckduckgo-search
  Downloading duckduckgo_search-8.0.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.11/dist-packages (from duckduckgo-search) (8.2.0)
Collecting primp>=0.15.0 (from duckduckgo-search)
  Downloading primp-0.15.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: lxml>=5.3.0 in /usr/local/lib/python3.11/dist-packages (from duckduckgo-search) (5.4.0)
Downloading duckduckgo_search-8.0.2-py3-none-any.whl (18 kB)
Downloading primp-0.15.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 70.6 MB/s eta 0:00:00
Installing collected packages: primp, duckduckgo-search
Successfully installed duckduckgo-search-8.0.2 primp-0.15.0

In [ ]:
import re
from langchain.tools import DuckDuckGoSearchRun
from langchain_core.prompts import SystemMessagePromptTemplate, ChatPromptTemplate, HumanMessagePromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain.tools import DuckDuckGoSearchRun

# 1. Define the search tool using DuckDuckGo
search_tool = DuckDuckGoSearchRun()

class ExtractJsonRunnable(Runnable[str, str]):
    def invoke(self, text: str, config=None) -> str:
      m =  m = re.split(r"AI:\s*", text, re.DOTALL)
      if m:
        return m[1].strip()
      else:
        raise ValueError("Did Not find AI part!")

# 3. Define the SystemMessage and HumanMessage templates
system_message = SystemMessagePromptTemplate.from_template(
    "You are a helpful assistant that provides detailed info about football players. "
    "Use the provided context to answer accurately."
    'Please responce in json format as shown below, and avoid generating any more tokens: \n {{"full_name": "{player_name}", "nationality": "", "age": "", "current_club": "", "position": ""}}'
)

human_message = HumanMessagePromptTemplate.from_template(
    (
        "Context about the player:\n{context}\n\n"
        "Based on this context, provide the following info about {player_name}:\n"
        "- full name\n"
        "- nationality\n"
        "- age\n"
        "- current club\n"
        "- position\n\n"
        "Format the response like:\n"
        "{player_name}:\n"
        "  full_name: \n"
        "  nationality: \n"
        "  age: \n"
        "  current_club: \n"
        "  position: "
    )
)

prompt = ChatPromptTemplate.from_messages([system_message, human_message,AIMessagePromptTemplate.from_template("\n")])

# 5. Get search context for player using DuckDuckGo
def get_search_context(player_name):
    query = f"{player_name} football player biography"
    results = search_tool.run(query)
    if results and len(results) > 20:
        return results
    else:
        return "No additional context found."
parser = JsonOutputParser()
prompt = prompt.partial(
        context=search_tool.run("{player_name}'s biography"),
        format_instructions=parser.get_format_instructions())
footballer_chain =  prompt| llm | ExtractJsonRunnable() | parser

In [ ]:
# Batch the requests for multiple
batch_questions = [
  {"player_name": "Lionel Messi"},
  {"player_name": "Cristiano Ronaldo"},
  {"player_name": "Kylian Mbappé"},
  {"player_name": "Neymar"},
  {"player_name": "Declan Rice"},
  {"player_name": "Trent Alexander-Arnold"},
  {"player_name": "John Stones"},
  {"player_name": "Alphonso Davies"}
]
answers = footballer_chain.batch(batch_questions)

# Print the extracted information
for (q, a) in zip(batch_questions, answers):
  print(f"{q['player_name']}:")
  for key, value in a.items():
    print(f"  {key}: {value}")
  print()

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Lionel Messi:
  full_name: Lionel Messi
  nationality: Argentinian
  age: 37
  current_club: Paris Saint-Germain
  position: Forward

Cristiano Ronaldo:
  full_name: Cristiano Ronaldo
  nationality: Portuguese
  age: 37
  current_club: Al-Nassr
  position: Forward

Kylian Mbappé:
  full_name: Kylian Mbappé
  nationality: French
  age: 24
  current_club: Paris Saint-Germain
  position: Forward

Neymar:
  full_name: Neymar
  nationality: Brazilian
  age: 37
  current_club: Al-Nassr
  position: Forward

Declan Rice:
  full_name: Declan Rice
  nationality: English
  age: 28
  current_club: West Ham United
  position: Midfielder

Trent Alexander-Arnold:
  full_name: Trent Alexander-Arnold
  nationality: English
  age: 23
  current_club: Liverpool
  position: Right Back

John Stones:
  full_name: John Stones
  nationality: English
  age: As of 2023, John Stones is 35 years old.
  current_club: Manchester City
  position: Defender

Alphonso Davies:
  full_name: Alphonso Davies
  nationality: Canadian
  age: 23
  current_club: Bayern Munich
  position: Forward

## 3. Build a RAG pipeline (26 points + 3)

In this section, We use a subset of [RecipeNLG](https://recipenlg.cs.put.poznan.pl) dataset to build our RAG pipelines. The dataset contains recipes and their corresponding instructions.

You can download the subset from [this google drive link](https://drive.google.com/file/d/1mgPcQKc7-SaWVyxaJ404L6dGkQvODca5/view?usp=sharing) or from the course website.

### 3.1 Load and prepare the dataset (4 points)

#### Completion 5: (4 point)

First, you should load the dataset, which is stored in a CSV file. and converting it to a `datasets.Dataset` object.

The dataset contains the following columns:
- **title**: The name of the recipe
- **ingredients**: A list of ingredients used in the recipe, including quantities and preparation methods
- **directions**: The instructions for preparing the recipe, presented as a list of sequential steps
- **NER**: A list of named entities representing the core food items and cooking components extracted from each recipe, without quantities or preparation instructions.

**Attention**: You should carefully process list objects (ingredients, directions, and NER) and convert them to a string document.

**Attention 2**: The provided dataset, has 5k recipes. You can use a smaller subset of the dataset for your experiments. For example, you can use the first 100 recipes for your experiments or more, based on your resource limitation.

In [1]:
!pip install -q gdown datasets

In [2]:

!pip install --upgrade datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (2.14.4)
Collecting datasets
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.31.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.11.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 36.4 MB/s eta 0:00:00
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 19.0 MB/s eta 0:00:00
Installing collected packages: fsspec, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
  Attempting uninstall: datasets
    Found existing installation: datasets 2.14.4
    Uninstalling datasets-2.14.4:
      Successfully uninstalled datasets-2.14.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.6.0 fsspec-2025.3.0

In [3]:
!gdown 1mgPcQKc7-SaWVyxaJ404L6dGkQvODca5 -O data_5000.csv

Downloading...
From: https://drive.google.com/uc?id=1mgPcQKc7-SaWVyxaJ404L6dGkQvODca5
To: /content/data_5000.csv
100% 5.92M/5.92M [00:00<00:00, 143MB/s]

In [1]:
import gdown
from datasets import load_dataset

# دانلود فایل CSV از Google Drive
url = 'https://drive.google.com/uc?id=1mgPcQKc7-SaWVyxaJ404L6dGkQvODca5'
gdown.download(url, 'data_5000.csv', quiet=False)

# بارگذاری و پردازش دیتاست
dataset = load_dataset('csv', data_files='data_5000.csv', split='train')

# نمایش دیتاست
print(dataset)

Downloading...
From: https://drive.google.com/uc?id=1mgPcQKc7-SaWVyxaJ404L6dGkQvODca5
To: /content/data_5000.csv
100%|██████████| 5.92M/5.92M [00:00<00:00, 160MB/s]

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['Unnamed: 0', 'title', 'ingredients', 'directions', 'NER'],
    num_rows: 5000
})

In [2]:
from langchain_core.documents import Document
import pandas as pd

# فرض می‌کنیم دیتاست را قبلاً اینجا بارگذاری کردید
df = pd.read_csv('data_5000.csv')

documents: list[Document] = []

# تبدیل هر ردیف به Document
for _, row in df.iterrows():
    # ساخت متن ساده از ردیف، مثلا همه ستون‌ها را به صورت "کلید: مقدار" جدا شده با سطر جدید
    content = "\n".join(f"{col}: {row[col]}" for col in df.columns)
    doc = Document(page_content=content)
    documents.append(doc)

print(f"Number of documents: {len(documents)}")

Number of documents: 5000

In [3]:
sample_documents = documents[:1000]

print(f"Number of sample documents: {len(sample_documents)}")

Number of sample documents: 1000

In [4]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1024,
    chunk_overlap=128
)

chunks = text_splitter.split_documents(sample_documents)


print(f"Number of chunks: {len(chunks)}")

Number of chunks: 1965

### 3.2 Sparse Retriever (3 points)

In this section, we would create a sparse retriever for our RAG pipeline.

#### Question 5: (2 points)

1. Explain how a sparse retriever like TF-IDF represents documents and queries. How does this representation influence which documents are retrieved?
2. Sparse retrievers rely on exact token matches between queries and documents. What are the strengths and weaknesses of this approach, especially compared to dense retrievers?

TF-IDF is a sparse retrieval method that represents documents and queries using high-dimensional sparse vectors, where each dimension corresponds to a unique term in the vocabulary. These vectors are created using the TF-IDF formula, which assigns a weight to each term based on its importance. The term frequency (TF) captures how often a term appears in a specific document or query, while the inverse document frequency (IDF) measures how rare or common the term is across all documents, giving higher weight to rarer terms. Since most documents and queries contain only a small subset of the entire vocabulary, the resulting vectors are mostly zeros, making them sparse.
This sparsity makes retrieval more efficient, as calculating similarity between the query vector and document vectors—typically using cosine similarity—requires fewer computations due to the large number of zero entries. Documents that share many important terms (i.e., terms with high TF-IDF scores) with the query are assigned higher similarity scores, while those without overlapping or significant terms rank lower.
However, TF-IDF's reliance on exact term matching means it works best when the query and relevant documents use the same or very similar vocabulary. It struggles with vocabulary mismatch, such as synonyms, potentially missing relevant documents when different wording is used. Despite this limitation, TF-IDF remains efficient, interpretable, and effective for many retrieval tasks where exact word overlap plays a key role.

**Strengths of Sparse Retrievers (like TF-IDF):**

* **Interpretability:** Easy to understand why documents are retrieved—based on exact term matches and their importance.
* **Efficiency:** Fast indexing and retrieval using inverted indices, suitable for very large corpora.
* **Simplicity:** Requires no training; straightforward to implement and tune.
* **Good for keyword-based queries:** Works well when the query and documents share exact words.

---

**Weaknesses of Sparse Retrievers:**

* **Vocabulary mismatch:** Cannot handle synonyms, paraphrases, or related concepts well since it relies on exact token matching.
* **Limited semantic understanding:** Fails when relevant documents use different wording from the query.
* **Sparse representation limitations:** Cannot capture the contextual meaning or deeper relationships between words.

---

**Compared to Dense Retrievers:**

* **Dense retrievers** use continuous vector embeddings capturing semantic similarity, allowing them to match related concepts even if the exact words differ.
* Dense methods better handle paraphrasing, synonyms, and more natural language queries.
* However, dense retrievers typically require expensive training, more computation for indexing and retrieval, and are less interpretable.

#### Completion 6: (1 point)

Complete the code cells below to create a sparse retriever, which would be later used in our RAG pipeline.

In [7]:
!pip install langchain_community

Collecting langchain_community
  Downloading langchain_community-0.3.24-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.59 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (0.3.59)
Requirement already satisfied: langchain<1.0.0,>=0.3.25 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (0.3.25)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (2.0.40)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (3.11.15)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (9.1.2)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain_community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain_community)
  Downloading pydantic_settings-2.9.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: langsmith<0.4,>=0.1.125 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (0.3.42)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.20.0)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in /usr/local/lib/python3.11/dist-packages (from langchain<1.0.0,>=0.3.25->langchain_community) (0.3.8)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langchain<1.0.0,>=0.3.25->langchain_community) (2.11.4)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.59->langchain_community) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.59->langchain_community) (24.2)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.59->langchain_community) (4.13.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain_community) (3.10.18)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain_community) (0.23.0)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain_community)
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain_community) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain_community) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain_community) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain_community) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain_community) (2025.4.26)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain_community) (3.2.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain_community) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.59->langchain_community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.25->langchain_community) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.25->langchain_community) (2.33.2)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain_community) (1.3.1)
Downloading langchain_community-0.3.24-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 98.9 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.0-py3-none-any.whl (7.8 kB)
Downloading pydantic_settings-2.9.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 5.0 MB/s eta 0:00:00
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 5.5 MB/s eta 0:00:00
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: python-dotenv, mypy-extensions, marshmallow, httpx-sse, typing-inspect, pydantic-settings, dataclasses-json, langchain_community
Successfully installed dataclasses-json-0.6.7 httpx-sse-0.4.0 langchain_community-0.3.24 marshmallow-3.26.1 mypy-extensions-1.1.0 pydantic-settings-2.9.1 python-dotenv-1.1.0 typing-inspect-0.9.0

In [5]:
# Prepare your retriever. For this section, you should use a sparse retriever such as `TFIDF` or `BM25`.
# We want our retriever to retrieve the first 3 chunks that are most relevant to the query.
from langchain_community.retrievers import TFIDFRetriever

sparse_retriever = TFIDFRetriever.from_documents(
    documents=chunks,
    k=3
)

In [6]:
# Query below is related to `Zucchini Nut Bread` recipe.

Sample_query = "\
The kitchen smells warm and sweet already. \
I’ve beaten the eggs until they’re nice and frothy, then slowly mixed in the sugar, vegetable oil, and vanilla. \
it’s turned into a thick, glossy batter, smooth and golden. \
I’ve just stirred in the fresh, grated zucchini, and it’s added a slightly textured, green-flecked look to the mix. \
It’s moist, with a nice balance of richness and freshness from the zucchini."

# Use the sparse retriever to get the most relevant chunks for the query
retrieved_chunks = sparse_retriever.get_relevant_documents(Sample_query)[:3]

# Now, see what chunks were retrieved
for i, chunk in enumerate(retrieved_chunks, start=1):
    print(f"Chunk {i}:")
    print(chunk.page_content)
    print("Metadata:", chunk.metadata)
    print()

Chunk 1:
directions: ["Into a food processor with the metal blade, place the cream cheese.", "Cut the butter into a few pieces and add it with the motor running.", "Process until smooth and creamy.", "Add the sugar and vanilla extract and process until incorporated, scraping the sides of the bowl.", "Add the flour and the optional salt and pulse in just until the dough starts to clump together.", "Soften the cream cheese and butter.", "In a mixing bowl, cream the cream cheese and butter until blended.", "Beat in the sugar and vanilla extract.", "On low speed, beat in the flour and the optional salt until incorporated.", "Scrape the dough onto a piece of plastic wrap and press it together to form a ball.", "Divide the dough into 4 portions and cover each with plastic wrap.", "Refrigerate for 2 hours or overnight.", "In a medium bowl, combine the sugars, cinnamon, raisins, and walnuts and stir with a spatula or fork until well mixed.", "Remove the dough from the refrigerator and allow it to sit on the counter for about
Metadata: {}

Chunk 2:
directions: ["Prepare the ingredients.", "Combine and sift the 'A' ingredients.", "Cut the sweet potato into rounds and blanch in water to remove excess starch.", "Saute the sliced and blanched sweet potatoes in the butter.", "Lightly season with the sugar and soy sauce.", "Let cool.", "Bring the butter to room temperature (or gently warm in the microwave, being careful not to melt it).", "Cream the butter and sugar, adding the sugar in batches.", "Once the mixture has become creamy and past-like, gradually add in the beaten egg and mix.", "(Add it in gradually so that the mixture doesn't separate!)", "Gently fold in the sifted A ingredients in 2-3 batches.", "Once it is thoroughly mixed,", "Add in the rum.", "Transfer the batter into the mold.", "Here it is in muffin cups.", "Decorate with the sauteed sweet potatoes.", "Top with sesame seeds.", "Bake for 35 minutes at 170C and it's done.", "If making muffins, bake for 25 minutes at 170C.", "Optionally, spread rum on the top.", "Your aromatic rum and sweet
Metadata: {}

Chunk 3:
directions: ["In a saucepan boil the cider until it is reduced to about 1/4 cup and let it cool.", "In a bowl whisk together well the pumpkin puree, the eggs, the oil, the brown sugar, the zest, and the reduced cider.", "Into the bowl sift together the flour, the baking powder, the salt, the baking soda, the mace, the cinnamon, and the cloves, add the walnuts, and stir the batter until it is just combined.", "Transfer the batter to a well-buttered 8 1/2-by 4 1/2-inch loaf pan and bake the bread in the middle of a preheated 350F.", "oven for 1 hour, or until a tester comes out clean.", "Let the bread cool in the pan."]
NER: ["apple cider", "pumpkin puree", "eggs", "vegetable oil", "brown sugar", "orange zest", "flour", "double-acting baking powder", "salt", "baking soda", "ground mace", "cinnamon", "ground cloves", "walnuts"]
Metadata: {}

<ipython-input-6-98bc023c6aa3>:11: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  retrieved_chunks = sparse_retriever.get_relevant_documents(Sample_query)[:3]

### 3.3 Semantic Retriever (4 points)

#### Question 6: (2 point)

1. How does a semantic retriever represent documents and queries differently from a sparse retriever? Explain why this helps in cases where there are no exact word overlaps.
2. What role do embedding models (e.g., sentence-transformers) play in semantic retrieval? How does the choice of embedding model affect the retriever’s performance?

1. Semantic retrievers represent documents and queries using dense vector embeddings that capture the meaning and context of the text, rather than just counting exact word occurrences. Each document and query is converted into a continuous vector in a high-dimensional space, where similar meanings are placed close together, even if they don't share the same exact words.

This helps because when queries and documents use different wording but have similar meanings (e.g., synonyms, paraphrases), semantic retrievers can still match them based on their closeness in the embedding space. In contrast, sparse retrievers rely on exact token matches and fail when there's no direct word overlap.

2. Embedding models transform sentences or documents into dense vectors that encode their semantic content. Models like sentence-transformers are specially trained to produce embeddings that place semantically similar texts close together in the vector space.

The choice of embedding model greatly affects retriever performance because:

Quality of semantic understanding: Better models capture deeper context, nuances, and relationships, improving retrieval accuracy.

Domain adaptation: Models trained or fine-tuned on specific domains perform better on related queries/documents.

Vector dimensionality and efficiency: A balance between embedding size and retrieval speed impacts system scalability.

In short, a good embedding model enables semantic retrievers to find relevant documents even without exact word matches by understanding the meaning behind the text.

#### Completion 7: (2 point)

Let's create a semantic retriever. We would use `BAAI/bge-small-en` as our embedding model, and `FAISS` as our vector store. Complete the code cells below to create a semantic retriever, which would be later used in our RAG pipeline.

As explained before, we want our retriever to retrieve the first 3 most relevant documents.

In [10]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.11.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.11/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from faiss-cpu) (24.2)
Downloading faiss_cpu-1.11.0-cp311-cp311-manylinux_2_28_x86_64.whl (31.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.3/31.3 MB 53.4 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.11.0

In [7]:
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS

# 1. بارگذاری مدل embedding
embedding_model = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en")

# 2. ساخت وکتور استور FAISS با استفاده از اسناد (chunks) و embedding مدل
faiss_index = FAISS.from_documents(documents=chunks, embedding=embedding_model)

# 3. ساخت semantic retriever که 3 نتیجه برتر را برمی‌گرداند
semantic_retriever = faiss_index.as_retriever(search_type="similarity", search_kwargs={"k": 3})

<ipython-input-7-b6564d756d18>:5: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en")
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [8]:
# Query below is related to `Zucchini Nut Bread` recipe.

Sample_query = "\
The kitchen smells warm and sweet already. \
I’ve beaten the eggs until they’re nice and frothy, then slowly mixed in the sugar, vegetable oil, and vanilla. \
it’s turned into a thick, glossy batter, smooth and golden. \
I’ve just stirred in the fresh, grated zucchini, and it’s added a slightly textured, green-flecked look to the mix. \
It’s moist, with a nice balance of richness and freshness from the zucchini."

retrieved_chunks = semantic_retriever.get_relevant_documents(Sample_query)

# Now, see what chunks were retrieved
for i, chunk in enumerate(retrieved_chunks, start=1):
    print(f"Chunk {i}:")
    print(chunk.page_content)
    print("Metadata:", chunk.metadata)
    print()

Chunk 1:
Unnamed: 0: 4
title: Zucchini Nut Bread
ingredients: ["2 cups flour", "1 tablespoon cinnamon", "2 teaspoons baking soda", "1 teaspoon salt", "14 teaspoon baking powder", "3 eggs", "2 cups sugar", "1 cup vegetable oil", "1 tablespoon vanilla", "2 cups grated raw zucchini", "1 cup walnuts"]
directions: ["Sift dry ingredients.", "beat eggs untill frothy, add sugar, oil and vanilla.", "Beat untillthick.", "Stir in zucchini.", "blend in sifted dry ingredients.", "Fold in nuts.", "pour in greased loaf pan and bake at 350 degrees for 1 1/2 hours."]
NER: ["flour", "cinnamon", "baking soda", "salt", "baking powder", "eggs", "sugar", "vegetable oil", "vanilla", "zucchini", "walnuts"]
Metadata: {}

Chunk 2:
Unnamed: 0: 229
title: Baked Zucchini
ingredients: ["1 teaspoon olive oil", "1 pound zucchini, sliced 1/4-inch thick, at an angle", "Kosher salt and freshly ground black pepper", "Pinch of Hungarian paprika", "1/2 cup panko breadcrumbs (Japanese)", "1/4 cup grated Parmesan cheese", "8 sprigs fresh thyme, leaves stripped from the stem, lightly chopped", "1 tablespoon olive oil"]
Metadata: {}

Chunk 3:
directions: ["Preheat oven to 400 degrees.", "ln a large skillet over medium heat, heat olive oil until shimmering.", "Add onions and garlic, and saute until translucent, about 5 minutes.", "Add zucchini, squash, and eggplant, and saute until tender but have not lost their shape, about 10 minutes.", "Add tomatoes, thyme and parsley, and cook until tomatoes soften but do not lose their shape, about 5 minutes.", "Add red wine vinegar.", "Season with salt and pepper to taste.", "In a small bowl, mix 1 tablespoon flour with 3 tablespoons water.", "Mix well, and add to the vegetables.", "Cook for 3 minutes, stirring.", "Transfer to a baking sheet to cool until no longer steaming, then place in refrigerator to chill, uncovered, for 15 minutes.", "Place one sheet of puff pastry on a lightly floured work surface.", "Using a 3 1/2- to 4-inch-in-diameter cookie cutter or cup, cut out six disks.", "Using a 1-1/2 inch cookie cutter, cut out six more disks.", "Roll all the disks out to 1/8 inch thick.", "Butter or spray
Metadata: {}

### 3.4 Create RAG pipelines (6 points)

#### Question 7: (2 points)

1. What are the main components of a RAG system, and how do they interact during inference? Describe the flow from user input to model output.
2. Describe two different strategies for integrating retrieved context into the prompt. What are the trade-offs between these approaches?

1. **Main Components of a RAG System and Their Interaction During Inference:**

* **Retriever:**
  Receives the user input (query) and searches a large document collection to find the most relevant documents or passages related to the query. This can be a sparse retriever (like TF-IDF) or a dense retriever (using embeddings).

* **Generator:**
  A language model that takes the retrieved documents along with the original query and generates a natural language response. The generator uses the retrieved context to produce more informed, accurate, or up-to-date answers.

**Flow during inference:**
User inputs a query → Retriever fetches relevant documents → Retrieved documents and query are combined into a prompt → Generator produces the final output based on this enriched prompt → Output is returned to the user.

---

2. **Two Strategies for Integrating Retrieved Context into the Prompt and Their Trade-offs:**

* **Concatenation (Prepending the Context):**
  The retrieved documents are directly prepended or appended to the user query to form a single prompt fed into the language model.

  * *Pros:* Simple to implement; leverages the language model’s ability to read context.
  * *Cons:* Limited by prompt length; too much context can overwhelm the model or truncate important information.

* **Fusion-in-Decoder (FiD):**
  Retrieved documents are encoded separately and the decoder generates the answer by attending to all encoded documents jointly.

  * *Pros:* Allows handling many documents without prompt length limits; better at combining multiple pieces of information.
  * *Cons:* More complex architecture and higher computational cost.

#### Completion 8: (4 points)

Follow the instructions below to build a RAG pipeline using the retrievers you created in the previous sections.

In [9]:
Sample_query = """\
The kitchen smells warm and sweet already. \
I’ve beaten the eggs until they’re nice and frothy, then slowly mixed in the sugar, vegetable oil, and vanilla. \
it’s turned into a thick, glossy batter, smooth and golden. \
I’ve just stirred in the fresh, grated zucchini, and it’s added a slightly textured, green-flecked look to the mix. \
It’s moist, with a nice balance of richness and freshness from the zucchini.

What is your best guess about what am I cooking?\
"""

In [14]:
!pip install langchain_huggingface

Collecting langchain_huggingface
  Downloading langchain_huggingface-0.2.0-py3-none-any.whl.metadata (941 bytes)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.59 in /usr/local/lib/python3.11/dist-packages (from langchain_huggingface) (0.3.59)
Requirement already satisfied: tokenizers>=0.19.1 in /usr/local/lib/python3.11/dist-packages (from langchain_huggingface) (0.21.1)
Requirement already satisfied: transformers>=4.39.0 in /usr/local/lib/python3.11/dist-packages (from langchain_huggingface) (4.51.3)
Requirement already satisfied: sentence-transformers>=2.6.0 in /usr/local/lib/python3.11/dist-packages (from langchain_huggingface) (4.1.0)
Requirement already satisfied: huggingface-hub>=0.30.2 in /usr/local/lib/python3.11/dist-packages (from langchain_huggingface) (0.31.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (4.13.2)
Requirement already satisfied: langsmith<0.4,>=0.1.125 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (0.3.42)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (9.1.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (1.33)
Requirement already satisfied: pydantic<3.0.0,>=2.5.2 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (2.11.4)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (1.15.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (11.2.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.39.0->langchain_huggingface) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.39.0->langchain_huggingface) (2024.11.6)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.39.0->langchain_huggingface) (0.5.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (3.10.18)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (0.23.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.5.2->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.5.2->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.5.2->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.30.2->langchain_huggingface) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.30.2->langchain_huggingface) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.30.2->langchain_huggingface) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.30.2->langchain_huggingface) (2025.4.26)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (1.3.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers>=2.6.0->langchain_huggingface) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers>=2.6.0->langchain_huggingface) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.0.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-core<1.0.0,>=0.3.59->langchain_huggingface) (1.3.1)
Downloading langchain_huggingface-0.2.0-py3-none-any.whl (27 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.9 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 129.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 96.7 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 53.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.3 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.6 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.4 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 104.6 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, langchain_huggingface
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed langchain_huggingface-0.2.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [10]:
# We are going to use "microsoft/Phi-4-mini-instruct" as our LLM again. If you need, load it again here and as before.
from langchain_huggingface.llms import HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
model_id = "microsoft/Phi-4-mini-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id,
                device_map="cuda",
                torch_dtype="auto",
                trust_remote_code=False)

tokenizer.pad_token = tokenizer.eos_token
pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, max_new_tokens=200,top_p = 1,top_k = 50, eos_token_id=tokenizer.eos_token_id)

llm = HuggingFacePipeline(pipeline=pipe)

tokenizer_config.json:   0%|          | 0.00/2.93k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/3.91M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/15.5M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/249 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/587 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/2.50k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/16.3k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.77G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.90G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

Device set to use cuda

In [11]:
from langchain_core.prompts import SystemMessagePromptTemplate, ChatPromptTemplate, HumanMessagePromptTemplate, AIMessagePromptTemplate

system_message = SystemMessagePromptTemplate.from_template(
    "You are a helpful assistant that answers questions based on the provided context documents. "
    "Use the context carefully and provide clear, concise answers."
)

human_message = HumanMessagePromptTemplate.from_template(
    "Context:\n{context}\n\nQuestion:\n{question}"
)

ai_message = AIMessagePromptTemplate.from_template("{answer}")

prompt = ChatPromptTemplate.from_messages([
    system_message,
    human_message,
    ai_message
])

In [12]:
def get_context(question, retriever, top_k=3):
    docs = retriever.get_relevant_documents(question)
    top_docs = docs[:top_k]
    context = "\n\n".join([doc.page_content for doc in top_docs])
    return {"question": question, "context": context}

In [13]:
from langchain_core.runnables import RunnableLambda, RunnableMap
from langchain_core.output_parsers import StrOutputParser

output_parser = StrOutputParser()

get_question = RunnableLambda(lambda inputs: inputs["question"])

# اینجا به جای جداگانه گرفتن context و question، get_context کل دیکشنری را می‌سازد
get_context_runnable = RunnableLambda(lambda q: get_context(q, sparse_retriever, top_k=3))

# ساخت پرامپت از دیکشنری {question, context}
build_prompt = RunnableLambda(lambda inputs: f"Context:\n{inputs['context']}\n\nQuestion:\n{inputs['question']}\nAnswer:")

sparse_rag = (
    get_question
    | get_context_runnable  # حالا ورودی سوال رو می‌گیره و دیکشنری question+context میده بیرون
    | build_prompt          # پرامپت رو از دیکشنری می‌سازه
    | llm                  # پرامپت رو به مدل میده
)

response_text = sparse_rag.invoke({"question": Sample_query})

print(response_text)

Context:
directions: ["Prepare the ingredients.", "Combine and sift the 'A' ingredients.", "Cut the sweet potato into rounds and blanch in water to remove excess starch.", "Saute the sliced and blanched sweet potatoes in the butter.", "Lightly season with the sugar and soy sauce.", "Let cool.", "Bring the butter to room temperature (or gently warm in the microwave, being careful not to melt it).", "Cream the butter and sugar, adding the sugar in batches.", "Once the mixture has become creamy and past-like, gradually add in the beaten egg and mix.", "(Add it in gradually so that the mixture doesn't separate!)", "Gently fold in the sifted A ingredients in 2-3 batches.", "Once it is thoroughly mixed,", "Add in the rum.", "Transfer the batter into the mold.", "Here it is in muffin cups.", "Decorate with the sauteed sweet potatoes.", "Top with sesame seeds.", "Bake for 35 minutes at 170C and it's done.", "If making muffins, bake for 25 minutes at 170C.", "Optionally, spread rum on the top.", "Your aromatic rum and sweet

directions: ["Into a food processor with the metal blade, place the cream cheese.", "Cut the butter into a few pieces and add it with the motor running.", "Process until smooth and creamy.", "Add the sugar and vanilla extract and process until incorporated, scraping the sides of the bowl.", "Add the flour and the optional salt and pulse in just until the dough starts to clump together.", "Soften the cream cheese and butter.", "In a mixing bowl, cream the cream cheese and butter until blended.", "Beat in the sugar and vanilla extract.", "On low speed, beat in the flour and the optional salt until incorporated.", "Scrape the dough onto a piece of plastic wrap and press it together to form a ball.", "Divide the dough into 4 portions and cover each with plastic wrap.", "Refrigerate for 2 hours or overnight.", "In a medium bowl, combine the sugars, cinnamon, raisins, and walnuts and stir with a spatula or fork until well mixed.", "Remove the dough from the refrigerator and allow it to sit on the counter for about

directions: ["In a saucepan boil the cider until it is reduced to about 1/4 cup and let it cool.", "In a bowl whisk together well the pumpkin puree, the eggs, the oil, the brown sugar, the zest, and the reduced cider.", "Into the bowl sift together the flour, the baking powder, the salt, the baking soda, the mace, the cinnamon, and the cloves, add the walnuts, and stir the batter until it is just combined.", "Transfer the batter to a well-buttered 8 1/2-by 4 1/2-inch loaf pan and bake the bread in the middle of a preheated 350F.", "oven for 1 hour, or until a tester comes out clean.", "Let the bread cool in the pan."]
NER: ["apple cider", "pumpkin puree", "eggs", "vegetable oil", "brown sugar", "orange zest", "flour", "double-acting baking powder", "salt", "baking soda", "ground mace", "cinnamon", "ground cloves", "walnuts"]

Question:
The kitchen smells warm and sweet already. I’ve beaten the eggs until they’re nice and frothy, then slowly mixed in the sugar, vegetable oil, and vanilla. it’s turned into a thick, glossy batter, smooth and golden. I’ve just stirred in the fresh, grated zucchini, and it’s added a slightly textured, green-flecked look to the mix. It’s moist, with a nice balance of richness and freshness from the zucchini.

What is your best guess about what am I cooking?
Answer: Zucchini bread

Context:directions: ["In a saucepan boil the cider until it is reduced to about 1/4 cup and let it cool.", "In a bowl whisk together well the pumpkin puree, the eggs, the oil, the brown sugar, the zest, and the reduced cider.", "Into the bowl sift together the flour, the baking powder, the salt, the baking soda, the mace, the cinnamon, and the cloves, add the walnuts, and stir the batter until it is just combined.", "Transfer the batter to a well-buttered 8 1/2-by 4 1/2-inch loaf pan and bake the bread in the middle of a preheated 350F.", "oven for 1 hour, or until a tester comes out clean.", "Let the bread cool in the pan."]
NER: ["apple cider", "pumpkin puree", "eggs", "vegetable oil", "brown sugar", "orange zest", "

In [14]:
# Define get_context for semantic retriever
def get_semantic_context(question, retriever, top_k=3):
    docs = retriever.get_relevant_documents(question)
    top_docs = docs[:top_k]
    context = "\n\n".join([doc.page_content for doc in top_docs])
    return {"question": question, "context": context}

from langchain_core.runnables import RunnableLambda

# Assuming semantic_retriever is defined (e.g. FAISS or Annoy retriever with embeddings)

get_question = RunnableLambda(lambda inputs: inputs["question"])
get_context_runnable = RunnableLambda(lambda q: get_semantic_context(q, semantic_retriever, top_k=3))
build_prompt = RunnableLambda(lambda inputs: f"Context:\n{inputs['context']}\n\nQuestion:\n{inputs['question']}\nAnswer:")

semantic_rag = (
    get_question
    | get_context_runnable
    | build_prompt
    | llm
)

response_text = semantic_rag.invoke({"question": Sample_query})

response = {
    "question": Sample_query,
    "context": semantic_retriever.get_relevant_documents(Sample_query)[:3],
    "response": response_text,
}

print(response["response"])

Context:
Unnamed: 0: 229
title: Baked Zucchini
ingredients: ["1 teaspoon olive oil", "1 pound zucchini, sliced 1/4-inch thick, at an angle", "Kosher salt and freshly ground black pepper", "Pinch of Hungarian paprika", "1/2 cup panko breadcrumbs (Japanese)", "1/4 cup grated Parmesan cheese", "8 sprigs fresh thyme, leaves stripped from the stem, lightly chopped", "1 tablespoon olive oil"]

Unnamed: 0: 4
title: Zucchini Nut Bread
ingredients: ["2 cups flour", "1 tablespoon cinnamon", "2 teaspoons baking soda", "1 teaspoon salt", "14 teaspoon baking powder", "3 eggs", "2 cups sugar", "1 cup vegetable oil", "1 tablespoon vanilla", "2 cups grated raw zucchini", "1 cup walnuts"]
directions: ["Sift dry ingredients.", "beat eggs untill frothy, add sugar, oil and vanilla.", "Beat untillthick.", "Stir in zucchini.", "blend in sifted dry ingredients.", "Fold in nuts.", "pour in greased loaf pan and bake at 350 degrees for 1 1/2 hours."]
NER: ["flour", "cinnamon", "baking soda", "salt", "baking powder", "eggs", "sugar", "vegetable oil", "vanilla", "zucchini", "walnuts"]

Unnamed: 0: 240
title: Claudia's Zucchini Bread
ingredients: ["3 eggs", "2 cups sugar", "1 cup vegetable oil", "2 cups zucchini, grated", "2 teaspoons vanilla", "3 cups flour, sifted", "14 teaspoon baking powder", "1 teaspoon baking soda", "1 teaspoon salt", "1 tablespoon cinnamon", "34 cup nuts, chopped"]
directions: ["spray 2 9x5 loaf pans and set aside.", "Start oven at 325.", "Mix together:.", "eggs,sugar,oil,zucchini and vanilla.", "Add all the dry ingredients mixing well.", "Mix in the nuts.", "Divide batter evenly between the two pans.", "Bake at 325 for 60 minutes.", "The 2 loaves make 20 servings.serve."]
NER: ["eggs", "sugar", "vegetable oil", "zucchini", "vanilla", "flour", "baking powder", "baking soda", "salt", "cinnamon", "nuts"]

Question:
The kitchen smells warm and sweet already. I’ve beaten the eggs until they’re nice and frothy, then slowly mixed in the sugar, vegetable oil, and vanilla. it’s turned into a thick, glossy batter, smooth and golden. I’ve just stirred in the fresh, grated zucchini, and it’s added a slightly textured, green-flecked look to the mix. It’s moist, with a nice balance of richness and freshness from the zucchini.

What is your best guess about what am I cooking?
Answer: Zucchini Nut Bread
Explanation: The description of the batter turning into a thick, glossy mixture with a green-flecked look from the grated zucchini, and the mention of a balance of richness and freshness, matches the process of making Zucchini Nut Bread as described in the provided recipe. The other recipe, Baked Zucchini, does not involve a batter or a baking process that would result in a sweet, warm smell.

In [15]:
# Finally, let's try the same query with the LLM directly, without any retrieval.
response = llm.invoke(Sample_query)
print(response)

The kitchen smells warm and sweet already. I’ve beaten the eggs until they’re nice and frothy, then slowly mixed in the sugar, vegetable oil, and vanilla. it’s turned into a thick, glossy batter, smooth and golden. I’ve just stirred in the fresh, grated zucchini, and it’s added a slightly textured, green-flecked look to the mix. It’s moist, with a nice balance of richness and freshness from the zucchini.

What is your best guess about what am I cooking? I’m guessing a zucchini bread, but I’m not sure. I’ve never made it before, and I’m not sure if I have all the ingredients. I have flour, sugar, eggs, oil, and vanilla, but I don’t have any zucchini. I also don’t have any baking powder or baking soda, which I’ve read are necessary for a good rise. I’m not sure if I can just add some baking soda to the mix, or if I need to find a way to incorporate the zucchini without it. I’m also not sure if I need to preheat the oven, or if I can just put the batter in the oven and let it cook. I’m not sure if I need to grease the pan, or if the batter will stick to the pan. I’m also not sure if I need to add any other ingredients, like nuts or chocolate chips, to make it more interesting. I’m not sure if I should just go with the recipe I found,

### 3.5 Evaluate our pipelines (9 points)

In this section, we are going to evaluate our RAG pipelines. First, we would design 5 queries to evaluate our RAG pipelines and our LLM alone.

#### Completion 9: (1 point)

Add 4 more queries, similar to the example. The examples would be based on the first 100 recipes of our dataset.
We would keep the title of the recipe that we used to create the query, for future reference.

In [16]:
queries = [
    {
        "title": "Balsamic Chicken Pasta with Fresh Cheese",
        "query": "I am cooking dinner. Here is what my kitchen looks like:\nThe linguine is cooked and set aside. The red bell peppers are soft and slightly caramelized. The balsamic dressing is mixed with garlic, salt, pepper, and fresh basil. Each component is ready in its bowl, colorful and aromatic.\n\nWhat should I do as my next step?"
    },
    {
        "title": "Classic Beef Stroganoff",
        "query": "I'm preparing a hearty meal. The beef strips are browned and resting on the side. Mushrooms have been sautéed with onions and garlic. A creamy sauce is simmering on the stove. How should I combine these ingredients to finish the dish?"
    },
    {
        "title": "Lemon Garlic Roasted Salmon",
        "query": "In my kitchen, the salmon fillets are seasoned with salt, pepper, and fresh dill. Lemon slices are ready to be placed on top. The oven is preheated to 400°F. What are the next steps to roast the salmon perfectly?"
    },
    {
        "title": "Vegetable Stir Fry with Tofu",
        "query": "I've chopped broccoli, bell peppers, and snap peas. The tofu is pressed and cubed. Soy sauce and ginger mixture are prepared. How do I stir fry everything to keep the vegetables crisp and flavorful?"
    },
    {
        "title": "Chocolate Chip Banana Bread",
        "query": "My bananas are mashed and mixed with sugar and melted butter. Flour and baking soda are sifted and ready. Chocolate chips are waiting to be folded in. What’s the next step to prepare this banana bread batter?"
    }
]

In [17]:
from textwrap import fill
questions = [{"question": q["query"]} for q in queries]

llm_responses = llm.batch([q["query"] for q in queries])
sparse_rag_responses = sparse_rag.batch(questions)
semantic_rag_responses = semantic_rag.batch(questions)

In [ ]:

for query, r1, r2, r3 in zip(queries, llm_responses, sparse_rag_responses, semantic_rag_responses):
    print(f'{query["title"]}:')
    print(f'  - Without  RAG: {fill(r1, width=90, initial_indent="", subsequent_indent=" "*18)}')
    print(f'  - Sparse   RAG: {fill(r2, width=90, initial_indent="", subsequent_indent=" "*18)}')
    print(f'  - Semantic RAG: {fill(r3, width=90, initial_indent="", subsequent_indent=" "*18)}')
    print()

Balsamic Chicken Pasta with Fresh Cheese:
  - Without  RAG: I am cooking dinner. Here is what my kitchen looks like: The linguine is cooked and set
                  aside. The red bell peppers are soft and slightly caramelized. The
                  balsamic dressing is mixed with garlic, salt, pepper, and fresh basil.
                  Each component is ready in its bowl, colorful and aromatic.  What should
                  I do as my next step? To continue with your dinner preparation, you
                  should combine the cooked linguine with the prepared balsamic dressing
                  and the caramelized red bell peppers. Here's a step-by-step guide to
                  help you:  1. **Drain the Linguine**: If the linguine is still in its
                  cooking water, drain it to prevent the pasta from being too wet.  2.
                  **Combine Ingredients**: In a large mixing bowl, combine the cooked
                  linguine, the balsamic dressing, and the caramelized red bell peppers.
                  Toss everything together until the pasta is evenly coated with the
                  dressing and the peppers are well distributed.  3. **Season**: Taste the
                  mixture and adjust the seasoning if necessary. You might want to add a
                  bit more salt, pepper, or even a squeeze of lemon juice for extra
                  flavor.  4. **Serve**: Transfer the combined ingredients to a serving
                  dish. You can garnish with additional fresh basil leaves or a sprinkle
                  of Parmesan cheese if desired.  5. **Enjoy**: Serve the dish
  - Sparse   RAG: Context: directions: ["In a wide skillet large enough to accommodate the cooked pasta
                  later, warm the olive oil over medium-low heat.", "Add the garlic and
                  sausage and saute.", "When the garlic is well softened and fragrant and
                  the sausage is lightly browned, after about 7 minutes, add the beans.",
                  "Using a wooden spoon, stir them with the oil and break them up a
                  little.", "Stir in the bean liquid and the meat broth.", "Simmer,
                  uncovered, over medium-low heat until the liquid has thickened to a
                  sauce consistency, about 20 minutes.", "Meanwhile, bring a large pot
                  filled with water to a rolling boil.", "Stir in the pasta and the kosher
                  salt.", "Cook, always over the highest possible heat and stirring
                  constantly to prevent the strands from sticking together, until the
                  pasta is almost cooked.", "Cooking time depends on what type of pasta is
                  used.", "Fresh bigoli are cooked as soon as the water returns to the
                  boil and the noodles rise to the surface, about 3 minutes.", "Factory-
                  made bucatini cook quickly because they are  directions: ["Put oil and
                  butter in a skillet heat on medium heat.", "While skillet is heating
                  bring 4 quart Sauce pan of water to a boil.", "While your waiting for
                  water to boil add onion and garlic to skillet and saute unit onion is
                  almost transparent.", "Add linguine to 4 qt sauce pan and cook approx
                  7-10 min, until desired tenderness.", "While your linguine is cooking
                  add shrimp to skillet and cook 2-3 minutes, until shrimp is pink and
                  cooked through out.", "Once your shrimp is ready add parsley, walnuts,
                  olives, oregano, basil, salt and pepper to the skillet.", "Mix to
                  combine skillet ingredients.", "Remove from heat.", "When your Linguine
                  is done, drain it.", "Place about a cup to a cup and a half of linguine
                  on each plate and then spoon the skillet mixture over the to of the
                  linguine.", "Provide parmesan cheese for sprinkling."] NER: ["shrimp",
                  "olive oil", "butter", "onion", "garlic", "parsley", "walnuts", "green
                  olives", "oregano", "basil", "salt", "pepper", "parmesan cheese",
                  "linguine"]  directions: ["Cook linguine according to package
                  directions; drain.", "Saute bell pepper in a small skillet over medium
                  heat until limp, about 10 to 12 minutes.", "Meanwhile, whisk vinegar,
                  garlic, salt and pepper in a small bowl; slowly whisk in oil.", "Stir in
                  1/2 cup of basil.", "Place pasta, chicken, cooked peppers, mozzarella,
                  goat cheese, and remaining basil in a large bowl.", "Pour dressing over
                  top and toss to coat.", "Serves 4.", "Note: when I make this, I put a
                  couple of uncooked chicken breasts, sprinkled with salt, pepper, and
                  garlic powder, under the broiler while everything else is being
                  prepared."] NER: ["weight Linguine", "Red Bell Pepper", "Balsamic
                  Vinegar", "Garlic", "Salt", "Black Pepper", "Olive Oil", "Fresh Basil",
                  "Chicken", "Mozzarella", "Goat Cheese Crumbles"]  Question: I am cooking
                  dinner. Here is what my kitchen looks like: The linguine is cooked and
                  set aside. The red bell peppers are soft and slightly caramelized. The
                  balsamic dressing is mixed with garlic, salt, pepper, and fresh basil.
                  Each component is ready in its bowl, colorful and aromatic.  What should
                  I do as my next step? Answer: Combine the cooked linguine, soft red bell
                  peppers, and balsamic dressing in a large bowl, then add uncooked
                  chicken breasts, sprinkle with salt, pepper, and garlic powder, and
                  broil until the chicken is cooked through.
  - Semantic RAG: Context: directions: ["Cook linguine according to package directions; drain.", "Saute bell
                  pepper in a small skillet over medium heat until limp, about 10 to 12
                  minutes.", "Meanwhile, whisk vinegar, garlic, salt and pepper in a small
                  bowl; slowly whisk in oil.", "Stir in 1/2 cup of basil.", "Place pasta,
                  chicken, cooked peppers, mozzarella, goat cheese, and remaining basil in
                  a large bowl.", "Pour dressing over top and toss to coat.", "Serves 4.",
                  "Note: when I make this, I put a couple of uncooked chicken breasts,
                  sprinkled with salt, pepper, and garlic powder, under the broiler while
                  everything else is being prepared."] NER: ["weight Linguine", "Red Bell
                  Pepper", "Balsamic Vinegar", "Garlic", "Salt", "Black Pepper", "Olive
                  Oil", "Fresh Basil", "Chicken", "Mozzarella", "Goat Cheese Crumbles"]
                  Unnamed: 0: 851 title: Grilled Fish Over Linguine With Roasted Pepper
                  Sauce ingredients: ["2 red peppers", "4 firm-textured fish fillets or
                  steaks, such as halibut (about 1-1/4 lb.)", "1 tsp. lemon pepper
                  seasoning", "1/4 lb. (4 oz.) 2% Milk VELVEETA, cut up", "8 oz. hot
                  cooked spinach linguine"]  cayenne pepper to taste if you like it really
                  spicy.", "Serve over favourite pasta cooked according to package
                  directions.", "I recommend linguine."]  Question: I am cooking dinner.
                  Here is what my kitchen looks like: The linguine is cooked and set
                  aside. The red bell peppers are soft and slightly caramelized. The
                  balsamic dressing is mixed with garlic, salt, pepper, and fresh basil.
                  Each component is ready in its bowl, colorful and aromatic.  What should
                  I do as my next step? Answer: Combine the cooked linguine, soft red bell
                  peppers, and balsamic dressing in a large bowl, then top with chicken,
                  mozzarella, and goat cheese before serving.

Classic Beef Stroganoff:
  - Without  RAG: I'm preparing a hearty meal. The beef strips are browned and resting on the side.
                  Mushrooms have been sautéed with onions and garlic. A creamy sauce is
                  simmering on the stove. How should I combine these ingredients to finish
                  the dish? To finish your hearty meal, you can follow these steps to
                  combine the beef strips, sautéed mushrooms, onions, garlic, and creamy
                  sauce:  1. **Prepare the Beef Strips**: Since the beef strips are
                  resting, you can now add them to the pan. If they are not already
                  browned, you can quickly brown them in a separate pan to add more
                  flavor.  2. **Combine the Ingredients**: Add the browned beef strips to
                  the pan with the sautéed mushrooms, onions, and garlic. Stir to combine
                  and let the beef cook for a few minutes to absorb the flavors from the
                  mushrooms, onions, and garlic.  3. **Add the Creamy Sauce**: Pour the
                  simmering creamy sauce into the pan with the beef and vegetables. Stir
                  well to ensure that the sauce coats all the ingredients evenly.  4.
                  **Simmer and Thicken**: Let the mixture simmer for a few more minutes to
                  allow the flavors to meld together. If the sauce is too thin,
  - Sparse   RAG: Context: directions: ["Cut the lamb shoulder across the grain in thin slices with a sharp
                  knife, flatten the slices between sheets of plastic wrap until they are
                  1/8 inch thick, and cut them into 1-inch-wide strips.", "In a saucepan
                  whisk together the lemon juice, the thyme, the rosemary, the oregano,
                  the pepper, and the salt, add the oil in a stream, whisking, and whisk
                  the marinate until it is emulsified.", "Add the lamb strips, stir the
                  mixture to coat the strips well with the marinade, and thread them onto
                  the skewers, reserving the remaining marinade.", "Arrange the kebabs on
                  the rack of a broiling pan, broil them under a preheated broiler about 3
                  inches from the heat, turning them once, for 6 minutes, and transfer
                  them to a plate.", "Transfer 2 tablespoons of the juice from the broiler
                  pan to the reserved marinade and bring the mixture to a boil.", "Remove
                  the pan from the heat, whisk in the yogurt and salt and pepper to taste,
                  and spoon the sauce over the kebabs."]  directions: ["Brush the
                  mushrooms clean and cut them as needed so that they are roughly equal in
                  size.", "In a large frying pan over medium heat, melt the butter.", "Add
                  the onion and saute until softened, about 3 minutes.", "Add the
                  mushrooms, increase heat to med-high and saute until lightly browned in
                  places, 3-5 minutes.", "Season to taste with salt and pepper and add the
                  wine.", "Increase heat to high and cook until the wine is nearly
                  evaporated, about 3 minutes.", "Add the stock and dried mushrooms,
                  decrease heat to medium, and cook until the fresh mushrooms are tender
                  and the dried mushrooms are rehydrated, about 10 minutes.", "Stir in 1/2
                  cup cream and nutmeg, then taste and adjust the seasoning.", "Add more
                  cream as desired to create a creamy but light sauce.", "Transfer to a
                  warmed serving dish, sprinkle with the chives and serve at once."]
                  directions: ["Preheat the oven to 350 F. Butter or oil an 8-inch baking
                  dish.", "Cook the penne 2 minutes less than package directions.", "(It
                  will finish cooking in the oven.)", "Rinse the pasta in cold water and
                  set aside.", "Combine the cooked pasta and the sauce in a medium bowl
                  and mix carefully but thoroughly.", "Scrape the pasta into the prepared
                  baking dish.", "Sprinkle the top with the cheeses and then the chili
                  powder.", "Bake, uncovered, for 20 minutes.", "Let the mac and cheese
                  sit for 5 minutes before serving.", "Melt the butter in a heavy-bottomed
                  saucepan over medium heat and whisk in the flour.", "Continue whisking
                  and cooking for 2 minutes.", "Slowly add the milk, whisking
                  constantly.", "Cook until the sauce thickens, about 10 minutes, stirring
                  frequently.", "Remove from the heat.", "Add the cheeses, salt, chili
                  powder, and garlic powder.", "Stir until the cheese is melted and all
                  ingredients are incorporated, about 3 minutes.", "Use immediately, or
                  refrigerate for up to 3 days.", "This  Question: I'm preparing a hearty
                  meal. The beef strips are browned and resting on the side. Mushrooms
                  have been sautéed with onions and garlic. A creamy sauce is simmering on
                  the stove. How should I combine these ingredients to finish the dish?
                  Answer: Preheat the oven to 350 F. Butter or oil an 8-inch baking dish.
                  Cook the penne 2 minutes less than package directions. Rinse the pasta
                  in cold water and set aside. Combine the cooked pasta and the sauce in a
                  medium bowl and mix carefully but thoroughly. Scrape the pasta into the
                  prepared baking dish. Sprinkle the top with the cheeses and then the
                  chili powder. Bake, uncovered, for 20 minutes. Let the mac and cheese
                  sit for 5 minutes before serving. Melt the butter in a heavy-bottomed
                  saucepan over medium heat and whisk in the flour. Continue whisking and
                  cooking for 2 minutes. Slowly add the milk, whisking constantly. Cook
                  until the sauce thickens, about 10 minutes, stirring frequently. Remove
                  from the heat. Add the cheeses, salt, chili powder, and garlic powder.
                  Stir until the cheese is melted and all ingredients are incorporated,
                  about 3 minutes. Use immediately, or refrigerate for up to
  - Semantic RAG: Context: directions: ["Preheat oven to 375 F.", "Put the beef cubes into a bowl and toss
                  with flour, 1/2 tablespoon salt and 1/2 teaspoon pepper.", "Add half of
                  the olive oil into the bottom of a large oven-safe pot and heat on high
                  heat.", "Add beef in a layer and sear for about a minute or two before
                  flipping.", "Turn heat to medium and sear on all sides for a minute or
                  two then remove beef from pot to a plate.", "Turn to medium-low and add
                  the other half of the olive oil.", "Then add mushrooms.", "Cook
                  mushrooms until soft.", "Add the onions and mix around until onions have
                  softened and started to really caramelize.", "Get all the bits from the
                  bottom of the pot while mixing.", "Add the garlic and mix.", "Cook for
                  another minute.", "Mix in beef, remainder of salt and pepper, paprika,
                  thyme, tomato paste and Worcestershire sauce.", "Add tomatoes and red
                  chili pepper, and mix in.", "Add beef broth and mix in.", "Place lid on
                  top of pot and place in the oven for 45 to 60 minutes or until beef is
                  tender.", "When done,  Unnamed: 0: 348 title: Crock Pot Beef and
                  Mushroom Casserole ingredients: ["2 lbs steak, cubed (your choice)", "1
                  (4 ounce) can mushrooms, with liquid", "1 (10 1/2 ounce) can cream of
                  mushroom soup", "12 cup white wine"] directions: ["Place all ingredients
                  in the slow cooker and stir well.", "Cook on low for at least 8 hours."]
                  NER: ["mushrooms", "cream of mushroom soup", "white wine"]  Unnamed: 0:
                  729 title: Potato and Corned Beef Wedge ingredients: ["4 -5 medium
                  starchy potatoes, peeled and cooked", "340 g corned beef", "1 -2
                  teaspoon minced garlic", "spring onion, finely chopped", "2 cups grated
                  parmesan cheese", "fresh ground black pepper", "4 eggs", "1 tablespoon
                  prepared hot mustard"] directions: ["Mash the hot potatoes roughly with
                  the Corned Beef, garlic, spring onions, 1 1/2 cups of the cheese and
                  season well with pepper.", "Beat the eggs and mustard together and then
                  stir into the potato mixture.", "Pile into a greased and paper-lined
                  23cm loose-bottom cake tin and scatter over the remaining cheese.",
                  "Bake at 180oC for 45 minutes.", "Cool in the tin before unmoulding.",
                  "Serve with tomato chutney and salad."] NER: ["starchy potatoes",
                  "corned beef", "garlic", "spring onion", "parmesan cheese", "fresh
                  ground black pepper", "eggs"]  Question: I'm preparing a hearty meal.
                  The beef strips are browned and resting on the side. Mushrooms have been
                  sautéed with onions and garlic. A creamy sauce is simmering on the
                  stove. How should I combine these ingredients to finish the dish?
                  Answer: Add the beef strips back into the pot with the mushrooms,
                  onions, and garlic. Mix in the creamy sauce, then pour in beef broth and
                  let it simmer until the beef is tender. Cover and cook in the oven for
                  45 to 60 minutes.

Lemon Garlic Roasted Salmon:
  - Without  RAG: In my kitchen, the salmon fillets are seasoned with salt, pepper, and fresh dill. Lemon
                  slices are ready to be placed on top. The oven is preheated to 400°F.
                  What are the next steps to roast the salmon perfectly? To roast the
                  salmon perfectly, follow these steps:  1. Place the salmon fillets on a
                  baking sheet lined with parchment paper or a silicone baking mat. This
                  will prevent sticking and make cleanup easier.  2. Arrange the lemon
                  slices on top of the salmon fillets. The lemon will add a fresh, zesty
                  flavor and also help to keep the salmon moist during cooking.  3. Season
                  the salmon with additional salt and pepper if desired, or just use the
                  fresh dill and lemon for seasoning.  4. Place the baking sheet in the
                  preheated oven.  5. Roast the salmon in the oven for about 12-15
                  minutes, or until the salmon flakes easily with a fork. The exact
                  cooking time may vary depending on the thickness of the fillets.  6.
                  Once the salmon is cooked, remove it from the oven and let it rest for a
                  few minutes before serving. This will allow the juices to redistribute
                  throughout the fillet, resulting in a more flavorful and moist salmon.
                  7. Serve
  - Sparse   RAG: Context: Unnamed: 0: 743 title: Double Salmon Cakes ingredients: ["2 slices rye bread",
                  "12 ounces boneless skinless salmon, cut into 1 inch pieces", "2 ounces
                  smoked salmon, cut into 1 inch pieces", "1 12 tablespoons Dijon
                  mustard", "2 tablespoons fresh dill (or 2 tsp dried)", "salt and

#### Report 2: (2 points)

Write a report about the experiments above. Your report should address the following:
1. Compare the quality of the answers. In which cases did Sparse or Semantic RAG help improve the response? Was there any example where it hurt the performance?
2. Discuss the differences between Sparse and Semantic RAG. Based on your examples, which one seems more effective and why?
3. Any surprising findings or patterns? Did anything behave differently than you expected?

### 1. Comparison of Answer Quality:

When comparing the quality of responses, **Sparse RAG** performed well in scenarios where the query contained exact keywords matching the documents. For instance, in the example of the "Balsamic Chicken Pasta with Fresh Cheese" recipe, Sparse RAG retrieved highly accurate cooking steps because the recipe instructions used the same phrases as the query. It worked effectively when the query and the documents shared precise terminology.

On the other hand, **Semantic RAG** excelled in situations where the query wording differed but the underlying meaning was similar. It was able to understand the broader context and provide relevant answers even when there were no exact keyword matches. In some cases, Sparse RAG's strict reliance on exact matches caused it to miss important context, whereas Semantic RAG compensated by capturing the meaning behind the words.

However, Semantic RAG wasn't flawless. In certain cases, it retrieved documents that were semantically similar but less relevant, resulting in slightly less precise answers. Despite this, the baseline responses (without RAG) were often generic and lacked specific instructions, highlighting the clear advantage of retrieval augmentation.

### 2. Differences Between Sparse and Semantic RAG:

The key difference between the two methods lies in their approach to retrieval. **Sparse RAG**, which uses techniques like TF-IDF, relies on exact token matching. This makes it highly effective when queries and documents share precise terminology, delivering accurate results in keyword-driven tasks. However, it struggles with queries that involve synonyms or paraphrased wording, leading to poor recall.

In contrast, **Semantic RAG** uses embedding models to understand the context and meaning behind words. This allows it to retrieve documents that are conceptually related to the query, even if there is no direct word overlap. As a result, Semantic RAG is better suited for handling queries with paraphrased or conceptually similar wording. Overall, Semantic RAG tends to provide more contextually relevant information, especially when exact query-document matches are sparse.

That said, Sparse RAG can outperform Semantic RAG in cases where exact phrasing is critical and the document corpus is well-aligned with the query vocabulary. This suggests that the choice of retriever depends on the specific needs of the task.

### 3. Surprising Findings or Patterns:

One surprising observation was that **Semantic RAG**, despite its ability to understand context, occasionally retrieved documents that were off-topic. This led to answers that were less precise, emphasizing the importance of high-quality embedding models and well-curated document corpora.

Another notable finding was that responses generated without any retrieval augmentation were consistently less detailed and more generic. This reinforced the importance of integrating external knowledge through retrieval to improve the quality and specificity of answers.

Interestingly, in cases involving recipes with very specific or unusual steps, Sparse RAG sometimes struggled due to its reliance on exact matches. Semantic RAG, in contrast, performed better by understanding the overall context of the recipe. These observations suggest that a hybrid approach combining both Sparse and Semantic RAG could strike the right balance between precision and recall, potentially delivering the most accurate and relevant results.

#### Completion 10: (3 points)

Now we want to automate the evaluation process. For this purpose, we are going to use the `ragas`. Follow the instructions of each cell to create the evaluation pipeline. To learn more about this framework, please refer to its [get started](https://docs.ragas.io/en/stable/getstarted/) or [how-to](https://docs.ragas.io/en/stable/howtos/) pages.

In [18]:
!pip install -q ragas rapidfuzz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 kB 17.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 98.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.9/62.9 kB 6.2 MB/s eta 0:00:00

In [19]:
!pip install --upgrade ragas

Requirement already satisfied: ragas in /usr/local/lib/python3.11/dist-packages (0.2.15)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from ragas) (2.0.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (from ragas) (3.6.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.11/dist-packages (from ragas) (0.9.0)
Requirement already satisfied: langchain in /usr/local/lib/python3.11/dist-packages (from ragas) (0.3.25)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.11/dist-packages (from ragas) (0.3.59)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.11/dist-packages (from ragas) (0.3.24)
Requirement already satisfied: langchain_openai in /usr/local/lib/python3.11/dist-packages (from ragas) (0.3.17)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from ragas) (1.6.0)
Requirement already satisfied: appdirs in /usr/local/lib/python3.11/dist-packages (from ragas) (1.4.4)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ragas) (2.11.4)
Requirement already satisfied: openai>1 in /usr/local/lib/python3.11/dist-packages (from ragas) (1.78.1)
Requirement already satisfied: diskcache>=5.6.3 in /usr/local/lib/python3.11/dist-packages (from ragas) (5.6.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai>1->ragas) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai>1->ragas) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai>1->ragas) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai>1->ragas) (0.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai>1->ragas) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai>1->ragas) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai>1->ragas) (4.13.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ragas) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ragas) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ragas) (0.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (2.32.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (0.70.15)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->ragas) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (0.31.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets->ragas) (6.0.2)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in /usr/local/lib/python3.11/dist-packages (from langchain->ragas) (0.3.8)
Requirement already satisfied: langsmith<0.4,>=0.1.17 in /usr/local/lib/python3.11/dist-packages (from langchain->ragas) (0.3.42)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain->ragas) (2.0.40)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-core->ragas) (9.1.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain-community->ragas) (3.11.15)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /usr/local/lib/python3.11/dist-packages (from langchain-community->ragas) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from langchain-community->ragas) (2.9.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from langchain-community->ragas) (0.4.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.11/dist-packages (from tiktoken->ragas) (2024.11.6)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->ragas) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->ragas) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->ragas) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->ragas) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->ragas) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->ragas) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->ragas) (1.20.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai>1->ragas) (3.10)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (0.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai>1->ragas) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai>1->ragas) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>1->ragas) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core->ragas) (3.0.0)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.17->langchain->ragas) (3.10.18)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.17->langchain->ragas) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.17->langchain->ragas) (0.23.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain-community->ragas) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets->ragas) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets->ragas) (2.4.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain->ragas) (3.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets->ragas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets->ragas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets->ragas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets->ragas) (1.17.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (1.1.0)

In [20]:
# Load the LLM as ragas llm. For this, we can use the provided wrapper for our existing LLM.

from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings
ragas_llm = LangchainLLMWrapper(llm)
ragas_embedding = LangchainEmbeddingsWrapper(embedding_model)

In [21]:
# Generate 10 test cases, using ragas, based on your documents. You can use a subset of your documents for faster runtime.
from datasets import Dataset
from ragas import EvaluationDataset
# بارگذاری دیتاست csv
df = pd.read_csv('data_5000.csv')

# ایجاد ستون سوال و جواب فرضی (برای مثال)
df['user_input'] = df['directions'].apply(lambda x: f"What is the next step after: {x[:50]}...?")  # نمونه ساده
df['response'] = df['directions']  # فرض اینکه پاسخ درست همان directions است

# تبدیل pandas DataFrame به datasets.Dataset
dataset = Dataset.from_pandas(df)

# حالا EvaluationDataset رو بساز
eval_dataset = EvaluationDataset.from_hf_dataset(dataset)

In [22]:
test_df = eval_dataset.to_pandas()
test_df.head(3)

,user_input,response
0,"What is the next step after: [""Preheat the ove...","[""Preheat the oven to 350 F. Butter or oil an ..."
1,"What is the next step after: [""Cook macaroni a...","[""Cook macaroni according to package direction..."
2,"What is the next step after: [""Add the tomatoe...","[""Add the tomatoes to a food processor with a ..."

In [23]:
test_questions = test_df["user_input"].values.tolist()
test_ground_truths = test_df["response"].values.tolist()

In [34]:
results = {
    "sparse": {
        "answers": [],
        "contexts": []
    },
    "dense": {
        "answers": [],
        "contexts": []
    },
}

LEN = 5

for question in test_questions[:LEN]:
    q = {"question": question}

    # بازیابی context جدا از پاسخ
    s_context_docs = sparse_retriever.get_relevant_documents(question)[:3]
    d_context_docs = semantic_retriever.get_relevant_documents(question)[:3]

    # اجرای pipeline‌ها برای دریافت پاسخ (که متنی شامل context و جواب است)
    s_response_text = sparse_rag.invoke(q)
    d_response_text = semantic_rag.invoke(q)

    # استخراج فقط پاسخ از متن خروجی مدل
    # فرض می‌کنیم پاسخ بعد از "Answer:" در متن آمده
    def extract_answer(text):
        split_token = "Answer:"
        if split_token in text:
            return text.split(split_token)[-1].strip()
        return text.strip()

    s_answer = extract_answer(s_response_text)
    d_answer = extract_answer(d_response_text)

    results["sparse"]["answers"].append(s_answer)
    results["sparse"]["contexts"].append([doc.page_content for doc in s_context_docs])

    results["dense"]["answers"].append(d_answer)
    results["dense"]["contexts"].append([doc.page_content for doc in d_context_docs])

In [35]:
from datasets import Dataset

sparse_response_dataset = Dataset.from_dict({
    "user_input": test_questions[:LEN],
    "response": results["sparse"]["answers"],
    "retrieved_contexts": results["sparse"]["contexts"],
    "reference": test_ground_truths[:LEN]
})

dense_response_dataset = Dataset.from_dict({
    "user_input": test_questions[:LEN],
    "response": results["dense"]["answers"],
    "retrieved_contexts": results["dense"]["contexts"],
    "reference": test_ground_truths[:LEN]
})

In [36]:
# Load ragas evaluation metrics. We would use all possible metrics, including:
# - Faithfulness
# - Answer relevancy
# - Answer correctness
# - retrieved context related metrics
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, LLMContextRecall
from ragas.metrics import ContextRelevance, LLMContextPrecisionWithReference,AnswerRelevancy,AnswerCorrectness

metrics = [ Faithfulness(), FactualCorrectness(),ContextRelevance(),AnswerRelevancy(),AnswerCorrectness(),LLMContextRecall(),LLMContextPrecisionWithReference()]

In [40]:
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings
llm = ChatOpenAI(
    model="o4-mini",
    base_url="https://api.avalai.ir/v1",
    api_key="aa-OcCC0sVoplWpEv9ntZE7Q3nZwgGHWyOKuAbGMaoAMnobXZql",
    max_tokens=4096,
    n=1,
    stop=None,
    temperature=0.1,
)
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-large",  # یا مدل مناسب امبدینگ Avalai
    base_url="https://api.avalai.ir/v1",
    openai_api_key="aa-OcCC0sVoplWpEv9ntZE7Q3nZwgGHWyOKuAbGMaoAMnobXZql",
)

In [41]:
# Use ragas evaluator to report the score of each pipeline, using the metrics defined above.
from ragas import evaluate
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

# from ragas.llms import LangchainLLMWrapper
# run_config = RunConfig(timeout=600)
# ragas_llm = LangchainLLMWrapper(llm)
# from ragas.embeddings import LangchainEmbeddingsWrapper
# ragas_embedding = LangchainEmbeddingsWrapper(embedding_model)

sparse_scores = evaluate(dataset=sparse_response_dataset,metrics=metrics, llm =llm, embeddings=embeddings)

dense_scores = evaluate(dataset=dense_response_dataset,metrics=metrics, llm = llm,embeddings=embeddings)

print(f"Sparse RAG Score: {sparse_scores}")
print(f"Dense RAG Score: {dense_scores}")


print(f"Sparse RAG Score: {sparse_scores}")
print(f"Dense RAG Score: {dense_scores}")

Evaluating:   0%|          | 0/35 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/35 [00:00<?, ?it/s]

Sparse RAG Score: {'faithfulness': 1.0000, 'factual_correctness(mode=f1)': 0.1220, 'nv_context_relevance': 0.4000, 'answer_relevancy': 0.5207, 'answer_correctness': 0.2276, 'context_recall': 0.4400, 'llm_context_precision_with_reference': 0.3000}
Dense RAG Score: {'faithfulness': 0.6000, 'factual_correctness(mode=f1)': 0.0960, 'nv_context_relevance': 0.2000, 'answer_relevancy': 0.4855, 'answer_correctness': 0.1945, 'context_recall': 0.0536, 'llm_context_precision_with_reference': 0.0000}
Sparse RAG Score: {'faithfulness': 1.0000, 'factual_correctness(mode=f1)': 0.1220, 'nv_context_relevance': 0.4000, 'answer_relevancy': 0.5207, 'answer_correctness': 0.2276, 'context_recall': 0.4400, 'llm_context_precision_with_reference': 0.3000}
Dense RAG Score: {'faithfulness': 0.6000, 'factual_correctness(mode=f1)': 0.0960, 'nv_context_relevance': 0.2000, 'answer_relevancy': 0.4855, 'answer_correctness': 0.1945, 'context_recall': 0.0536, 'llm_context_precision_with_reference': 0.0000}

In [42]:
sparse_scores.to_pandas().head(3)

,user_input,retrieved_contexts,response,reference,faithfulness,factual_correctness(mode=f1),nv_context_relevance,answer_relevancy,answer_correctness,context_recall,llm_context_precision_with_reference
0,"What is the next step after: [""Preheat the ove...","[directions: [""Cut the chicken into bite-sized...",[Place the potatoes in a baking dish and place...,"[""Preheat the oven to 350 F. Butter or oil an ...",1.0,0.00,0.0,0.351419,0.105122,0.0,0.0
1,"What is the next step after: [""Cook macaroni a...",[Unnamed: 0: 230\ntitle: Macaroni With Italian...,Drain the cooked macaroni.,"[""Cook macaroni according to package direction...",1.0,0.29,1.0,0.770838,0.357088,1.0,0.5
2,"What is the next step after: [""Add the tomatoe...","[directions: [""Cut the chicken into bite-sized...",[Add the remaining ingredients and blend until...,"[""Add the tomatoes to a food processor with a ...",1.0,0.12,0.0,0.529898,0.277330,0.0,0.0

In [43]:
dense_scores.to_pandas().head(3)

,user_input,retrieved_contexts,response,reference,faithfulness,factual_correctness(mode=f1),nv_context_relevance,answer_relevancy,answer_correctness,context_recall,llm_context_precision_with_reference
0,"What is the next step after: [""Preheat the ove...","[directions: [""Line a 9x13 pan with foil, leav...","[""Bake the crust for 15-20 minutes, until very...","[""Preheat the oven to 350 F. Butter or oil an ...",1.0,0.00,0.0,0.417661,0.114819,0.000,0.0
1,"What is the next step after: [""Cook macaroni a...",[Unnamed: 0: 666\ntitle: Macaroni and Cheese\n...,Set aside.,"[""Cook macaroni according to package direction...",1.0,0.00,1.0,0.000000,0.059501,0.125,0.0
2,"What is the next step after: [""Add the tomatoe...",[Unnamed: 0: 118\ntitle: Broiled Parmesan Toma...,The next step is to process the tomatoes until...,"[""Add the tomatoes to a food processor with a ...",0.0,0.31,0.0,0.764434,0.410887,0.000,0.0

In [51]:
sparse_df = sparse_scores.to_pandas()
sparse_df['Retriever'] = 'Sparse Retriever'

dense_df = dense_scores.to_pandas()
dense_df['Retriever'] = 'Dense Retriever'

combined_df = pd.concat([sparse_df, dense_df], ignore_index=True)

In [56]:
metrics_columns = [
    'faithfulness',
    'factual_correctness(mode=f1)',
    'nv_context_relevance',
    'answer_relevancy',
    'answer_correctness',
    'context_recall',
    'llm_context_precision_with_reference'
]

df_pivot = combined_df.pivot(index='user_input', columns='Retriever', values=metrics_columns)

df_pivot.columns.names = ['Metric', 'Retriever']
df_pivot = df_pivot.reset_index()

for metric in metrics_columns:
    df_pivot[(metric, 'Delta')] = df_pivot[(metric, 'Dense Retriever')] - df_pivot[(metric, 'Sparse Retriever')]

df_pivot.head()

Metric                                            user_input    faithfulness  \
Retriever                                                    Dense Retriever
0          What is the next step after: ["Add the tomatoe...             0.0
1          What is the next step after: ["Cook macaroni a...             1.0
2          What is the next step after: ["Pierce the skin...             0.0
3          What is the next step after: ["Preheat the ove...             1.0
4          What is the next step after: ["Sift dry ingred...             1.0

Metric                     factual_correctness(mode=f1)                   \
Retriever Sparse Retriever              Dense Retriever Sparse Retriever
0                      1.0                         0.31             0.12
1                      1.0                         0.00             0.29
2                      1.0                         0.00             0.00
3                      1.0                         0.00             0.00
4                      1.0                         0.17             0.20

Metric    nv_context_relevance                  answer_relevancy  \
Retriever      Dense Retriever Sparse Retriever  Dense Retriever
0                          0.0              0.0         0.764434
1                          1.0              1.0         0.000000
2                          0.0              0.0         0.553369
3                          0.0              0.0         0.417661
4                          0.0              1.0         0.692092

Metric                     answer_correctness  ...   context_recall  \
Retriever Sparse Retriever    Dense Retriever  ... Sparse Retriever
0                 0.529898           0.410887  ...              0.0
1                 0.770838           0.059501  ...              1.0
2                 0.573845           0.129338  ...              0.2
3                 0.351419           0.114819  ...              0.0
4                 0.377376           0.257785  ...              1.0

Metric    llm_context_precision_with_reference                  faithfulness  \
Retriever                      Dense Retriever Sparse Retriever        Delta
0                                          0.0              0.0         -1.0
1                                          0.0              0.5          0.0
2                                          0.0              0.0         -1.0
3                                          0.0              0.0          0.0
4                                          0.0              1.0          0.0

Metric    factual_correctness(mode=f1) nv_context_relevance answer_relevancy  \
Retriever                        Delta                Delta            Delta
0                                 0.19                  0.0         0.234536
1                                -0.29                  0.0        -0.770838
2                                 0.00                  0.0        -0.020476
3                                 0.00                  0.0         0.066242
4                                -0.03                 -1.0         0.314716

Metric    answer_correctness context_recall  \
Retriever              Delta          Delta
0                   0.133558       0.000000
1                  -0.297586      -0.875000
2                  -0.002983      -0.200000
3                   0.009696       0.000000
4                  -0.008302      -0.857143

Metric    llm_context_precision_with_reference
Retriever                                Delta
0                                          0.0
1                                         -0.5
2                                          0.0
3                                          0.0
4                                         -1.0

[5 rows x 22 columns]

#### Report 3: (1 point)

Compare the automated evaluation (using ragas) with your manual evaluation from the previous step. In your report, make sure to address the following:
1. How are the two evaluation methods different? Briefly describe what makes the automated evaluation distinct from your manual judgment process (e.g., consistency, objectivity, criteria used).
2.	Do both evaluations show the same results? Were the rankings or judgments about the quality of responses consistent between your analysis and the automated scores?
3.	If there were differences, why might that be? Reflect on what factors could lead to different results.

### Report 3: Comparison of Automated Evaluation (RAGAS) and Manual Evaluation

1. **Differences between Evaluation Methods**:
   The manual evaluation was subjective, based on human judgment considering the quality, relevance, and accuracy of the answers in context. It relied on qualitative insights and direct reading of examples.
   The automated evaluation using RAGAS is objective, consistent, and systematic. It quantifies metrics like faithfulness, factual correctness, answer relevancy, and context precision using predefined models and scoring functions, removing human biases but relying on model behavior.

2. **Consistency of Results**:
   While there were similarities in identifying which retrieval method (Sparse or Semantic) performed better overall, the automated evaluation sometimes produced scores that did not fully align with manual impressions. For example, some answers ranked higher by humans had lower automated scores, possibly due to nuances or context the model missed.

3. **Reasons for Differences**:
   The discrepancies likely arise because automated metrics depend on the LLM and embeddings used in scoring, which might interpret language differently from humans. Ambiguities, implicit knowledge, or subtle reasoning valued by humans may not be fully captured by automated metrics. Additionally, limited training or biases in the evaluation models can affect scores.

#### Question 8: (2 points)

1. Explain the underlying mechanism and techniques used by `ragas` to evaluate the performance of RAG pipelines. How does it ensure that the evaluation is both comprehensive and relevant to the task?

### Evaluating RAG Systems with Ragas: A Comprehensive Approach

Ragas is a sophisticated framework designed to assess Retrieval-Augmented Generation (RAG) systems by combining multiple metrics that provide a holistic view of performance. The tool goes beyond traditional evaluation methods, offering a nuanced and comprehensive analysis of how AI systems retrieve and generate information.

At its core, Ragas uses a multi-faceted approach to evaluate RAG pipelines. The framework employs several key techniques to ensure a thorough assessment. First, it leverages advanced language models to analyze the generated responses, checking for faithfulness, factual correctness, and relevance. This means the system doesn't just look at surface-level text matching, but deeply examines the semantic connections between queries, retrieved contexts, and generated answers.

The evaluation process is remarkably sophisticated. By using embedding-based similarity metrics, Ragas can understand the contextual nuances that traditional keyword-based methods might miss. For instance, it can detect when a response is semantically relevant even if it doesn't contain exact word matches. This approach provides a more intelligent and nuanced evaluation of RAG performance.

What sets Ragas apart is its flexibility and depth. The framework allows users to customize evaluation metrics based on specific use cases. Whether you're working on a complex question-answering system, a chatbot, or a content generation pipeline, Ragas can be tailored to provide meaningful insights. It breaks down the evaluation into multiple dimensions:

1. **Faithfulness**: Assessing how well the generated answer is supported by retrieved context
2. **Factual Correctness**: Verifying the accuracy of information against ground truth
3. **Answer Relevancy**: Measuring how precisely the answer addresses the original query
4. **Context Recall and Precision**: Evaluating the quality of retrieved information

The automated nature of Ragas is another significant advantage. By eliminating manual judgment, it provides consistent, repeatable evaluations that can be scaled across large datasets. The use of advanced language models simulates human-like understanding, capturing nuances that traditional evaluation methods might overlook.

Perhaps the most impressive aspect of Ragas is its ability to provide a 360-degree view of RAG system performance. It doesn't just focus on one aspect but examines the entire pipeline - from information retrieval to answer generation. This comprehensive approach helps developers and researchers identify specific areas of improvement, whether it's in context retrieval, answer generation, or semantic understanding.

For practitioners working with AI-powered information systems, Ragas offers an unprecedented level of insight. It goes beyond simple metrics to provide a deep, contextual understanding of how RAG systems perform. By breaking down complex interactions between retrieval and generation, it helps teams optimize their AI models with unprecedented precision.

The framework is particularly valuable in domains where accuracy and context are critical. Whether it's in scientific research, customer support, or complex information retrieval tasks, Ragas provides a robust method to validate and improve RAG systems. Its ability to quantify performance across multiple dimensions makes it an indispensable tool for AI researchers and developers.

As AI systems become increasingly complex, tools like Ragas become essential. They provide a scientific, data-driven approach to evaluating and improving retrieval-augmented generation systems. By offering a comprehensive, nuanced assessment, Ragas is helping to push the boundaries of what's possible in AI-powered information retrieval and generation.

#### Underlying Mechanism and Techniques:

1. **Multi-metric Evaluation**:
   `ragas` uses a set of carefully designed metrics such as:

   * *Faithfulness*: How well the generated answer is supported by the retrieved context.
   * *Factual Correctness*: Whether the answer is factually accurate compared to ground truth.
   * *Answer Relevancy*: How relevant the answer is to the user query.
   * *Context Recall and Precision*: How well the retrieved documents cover the information needed to answer the query.

2. **LLM-based Judgments**:
   Many of these metrics leverage language models (LLMs) to interpret, compare, and judge the text. For example, to check faithfulness or factual correctness, ragas prompts LLMs to analyze if the generated answer aligns with the context or reference answer.

3. **Embedding-based Similarity**:
   Some metrics use embeddings to compute semantic similarity between retrieved contexts and the question or answer, helping to quantitatively measure relevance beyond exact word matches.

4. **Flexible and Modular**:
   The framework allows combining different metrics depending on the task and available resources. This modularity ensures evaluation remains relevant and tailored.

5. **Automated and Scalable**:
   By automating these diverse evaluations, ragas provides consistent, repeatable, and scalable assessment without manual human judgment, increasing reliability.

### How it Ensures Comprehensiveness and Relevance:

* **Multiple Perspectives**: By evaluating generation quality, retrieval accuracy, and answer correctness separately, ragas captures a full picture of RAG pipeline performance.
* **Task-specific Adaptability**: Metrics can be chosen or tuned for specific domains or tasks, focusing evaluation on what's most important.
* **LLM Insight**: Using advanced LLMs for judgment simulates human-like understanding, making the evaluation sensitive to nuances beyond keyword matching.
* **Embedding Semantics**: Incorporating semantic similarity prevents over-reliance on surface-level text matches, ensuring context relevance is meaningfully measured.

### 3.6 (Optional) Other strategy: (3 points)

#### Question 9: (3 points)

There are other retriever strategies you can use to improve the performance of your RAG pipeline. In this task:
1. Explain what the `MultiQueryRetriever` does and how it can help improve retrieval quality in your pipeline.
2. Implement the `MultiQueryRetriever` in your RAG pipeline and evaluate its performance using both manual and automated methods.
3. You may also make additional improvements to your pipeline. If you do so, briefly explain what changes you made, how they affect the system, and why they might improve performance.

1. The MultiQueryRetriever is an innovative approach to document retrieval that significantly enhances the performance of RAG (Retrieval-Augmented Generation) systems by addressing one of the fundamental challenges in information retrieval: the variability in how queries can be expressed. At its core, this technique recognizes that a single question or information need can be phrased in multiple different ways, and that different phrasings may yield different but equally relevant results from a document store. 

What makes the MultiQueryRetriever particularly powerful is its use of language model capabilities to generate diverse query variations automatically. When a user submits their original query, the system doesn't just take that single input to search the document database. Instead, it employs an LLM to create several alternative formulations of that query. These aren't just simple synonym substitutions, but meaningful paraphrases that capture different aspects or perspectives of the original question. For example, if the original query is "What are the health benefits of green tea?", the system might generate variations like "How does drinking green tea improve health?", "What positive effects does green tea have on the body?", or "Why is green tea considered good for wellness?".

The real magic happens when all these query variations are used to search the document database independently. Each version might retrieve slightly different sets of relevant documents, and when combined, they provide a much more comprehensive set of potentially useful information than any single query could. This approach effectively casts a wider net while still maintaining relevance to the original information need. 

The improvement in retrieval quality manifests in several concrete ways. First, it dramatically increases recall - the system is more likely to find all relevant documents in the database because it's searching with multiple expressions of the same underlying need. Some documents might use terminology that matches one paraphrase better than the original query. Second, it enhances the system's ability to handle the natural variation in how people phrase questions. Users might express the same information need in many different ways, and the MultiQueryRetriever anticipates this by generating those variations proactively. 

Another significant advantage is that this method helps overcome vocabulary mismatch problems. In traditional retrieval systems, if a document uses different terminology than the query (even if the underlying meaning is the same), it might not be retrieved. By generating multiple phrasings, the MultiQueryRetriever increases the chances that at least one version will align well with how information is expressed in the documents.

The practical implementation typically involves running all generated queries against the retrieval system, then combining and deduplicating the results. The system might use simple union (all unique results from all queries) or more sophisticated methods like reciprocal rank fusion to combine the results in a way that prioritizes documents that perform well across multiple query variations. 

This technique proves particularly valuable in complex RAG applications where the quality of the final generated answer depends heavily on having the most relevant source material. By ensuring more comprehensive retrieval upfront, the subsequent generation step has better raw materials to work with, leading to more accurate, thorough, and nuanced final answers. It's worth noting that while this approach does require additional computational resources (since multiple queries need to be processed), the improvement in retrieval quality often justifies this cost, especially in applications where answer quality is critical. 

The MultiQueryRetriever represents an intelligent marriage of traditional information retrieval techniques with modern language model capabilities, creating a system that's more robust, more flexible, and ultimately more effective at understanding and fulfilling users' information needs. This makes it an increasingly popular choice for developers building sophisticated RAG applications across various domains, from customer support to research assistance to knowledge management systems.

In [ ]:
from langchain.chains import RetrievalQA
from langchain.retrievers import MultiQueryRetriever
from langchain.llms import HuggingFacePipeline  # Or your LLM wrapper
from langchain_community.retrievers import TFIDFRetriever

base_retriever = TFIDFRetriever.from_documents(documents=chunks, k=3)
multi_query_retriever = MultiQueryRetriever.from_llm(
    llm=llm,
    retriever=base_retriever,
    max_queries=5  
)
from langchain.chains import RetrievalQA

rag_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=multi_query_retriever,
    return_source_documents=True  
)
query = "How to prepare banana bread step by step?"
result = rag_chain.run(query)
print("Answer:", result['result'])
print("Sources:", [doc.page_content for doc in result['source_documents']])

### 3. Additional Improvements and Explanation

* **Increase `max_queries` in `MultiQueryRetriever`:** More paraphrases can increase retrieval diversity but might increase latency.

* **Use a better paraphrasing LLM:** A more accurate LLM for generating query variations will improve retrieval relevance.

* **Hybrid Retriever:** Combine sparse and dense retrievers by merging their top results to capture both lexical and semantic relevance.

* **Context Filtering:** After retrieval, apply filtering to keep only the highest quality or most relevant documents.

* **Prompt Tuning:** Improve generation quality by carefully designing prompt templates that better use retrieved documents.

---

**Why these might improve performance:**

* Multi-query retrieval broadens the search, helping to find documents that a single query misses.

* Better LLMs for paraphrasing lead to more meaningful query variations, thus more relevant results.

* Hybrid retrievers leverage strengths of both lexical and semantic methods.

* Filtering reduces noise, improving generator input.

* Prompt tuning enhances answer accuracy and fluency.

---

If you want, I can provide complete runnable code for this setup. Would you like that?

## 4. Read more: (10 points)

#### Cache-Augmented Generation (CAG): (4 points)

1. What is Cache-Augmented Generation (CAG)? How does it improve efficiency or performance during generation?
2. What are the similarities and differences between Cache-Augmented Generation (CAG) and Retrieval-Augmented Generation (RAG)? In what scenarios might you prefer one over the other?

Cache-Augmented Generation, or CAG, represents a significant optimization technique for modern language models that makes text generation more efficient by intelligently reusing computational work rather than performing redundant calculations. At its heart, CAG operates on a simple but powerful principle: why recompute what you've already figured out? When generating text word by word or token by token, language models often perform many similar calculations repeatedly, especially in their attention mechanisms where the same contextual information gets processed multiple times.  

The process works by storing intermediate results—like the key-value pairs in transformer models' attention layers—in a cache during text generation. As the model produces each new token, it can refer back to this cache rather than recalculating everything from scratch. This approach dramatically cuts down on unnecessary computation, making the entire generation process faster and more resource-efficient. For example, when generating a long response, the early parts of the text that have already been processed don’t need their attention states recomputed for every subsequent token; instead, the cached representations can be reused, saving both time and computational power.  

One of the most noticeable benefits of CAG is speed. Since the model isn't bogged down by redundant calculations, it can generate text more quickly, which is especially valuable in real-time applications like chatbots or interactive AI systems where low latency is crucial. Additionally, because caching reduces the computational load, it allows models to handle longer sequences without running into memory bottlenecks. This is particularly important for applications that require maintaining large contexts, such as document summarization or extended conversations, where processing lengthy inputs efficiently is essential.  

Beyond speed, CAG also improves resource efficiency. By minimizing redundant operations, it reduces the strain on GPU memory and processing power, making it more practical to deploy large language models in cost-sensitive or resource-constrained environments. This efficiency can translate into lower operational costs, better scalability, and the ability to run high-performance models on less powerful hardware.  

In practice, CAG is one of several optimizations that help make modern AI systems viable for real-world use. Whether in AI assistants, automated content generation, or other applications, the ability to generate text quickly and efficiently while maintaining high quality is a game-changer. By smartly reusing past computations rather than starting from zero at each step, Cache-Augmented Generation ensures that language models can deliver responsive, coherent, and context-aware outputs without unnecessary computational overhead. This makes CAG a key enabler for scalable, high-performance AI systems that need to balance speed, cost, and accuracy.

Cache-Augmented Generation (CAG) and Retrieval-Augmented Generation (RAG) are both techniques designed to enhance how language models generate text, but they approach the problem from fundamentally different angles. Understanding their similarities and differences helps determine when each method is most useful.

Both CAG and RAG share the broader goal of improving text generation beyond what a base language model can do alone. They operate on the principle that augmentation—whether through internal optimizations or external knowledge—can lead to better outcomes. CAG achieves this by reusing previously computed model states during generation, while RAG pulls in relevant documents or data from external sources to inform the model’s responses. In this sense, both methods rely on some form of additional information beyond the immediate input to enhance performance. However, the nature of that information and how it’s applied differ significantly.

The key distinction lies in their primary objectives. CAG is all about efficiency and speed. By caching intermediate computations—such as attention keys and values in transformer models—it avoids redundant calculations during text generation. This makes the process faster, reduces memory usage, and allows the model to handle longer sequences without excessive overhead. For example, in a chatbot that generates multi-turn conversations, CAG ensures that previously processed context isn’t recomputed from scratch at each step, leading to quicker responses. It doesn’t change the model’s knowledge or reasoning—just how efficiently it accesses what it already knows.

RAG, on the other hand, prioritizes knowledge and accuracy. Instead of optimizing internal computations, it dynamically retrieves relevant documents or data from an external knowledge base—such as Wikipedia, a proprietary database, or real-time web sources—and uses them to ground the model’s responses. This means the model can provide answers that are more factual, up-to-date, or domain-specific than what its base training data alone would allow. For instance, a customer support bot using RAG could pull the latest product manuals to answer user queries accurately, even if those details weren’t part of its original training.

Choosing between CAG and RAG depends on the specific needs of the application. If the priority is low latency, cost efficiency, or handling long contexts smoothly, CAG is the better choice. It’s ideal for real-time systems where speed matters, or where the base model’s knowledge is sufficient but needs to be accessed more efficiently. Meanwhile, RAG shines when factual correctness, access to dynamic knowledge, or domain expertise is critical. It’s the go-to method for question-answering systems, research assistants, or any scenario where responses must be grounded in external, verifiable information.

Interestingly, these techniques aren’t mutually exclusive. In some advanced systems, they can be combined—using CAG to accelerate the generation process while RAG ensures the content is accurate and informed by external data. This hybrid approach exemplifies how modern AI systems leverage multiple optimizations to balance speed, cost, and quality.

In summary, CAG and RAG represent two complementary paths to enhancing language models: one by making generation faster and leaner, the other by making it smarter and more informed. The right choice depends on whether the bottleneck is computational efficiency or knowledge depth—and in many cutting-edge applications, the answer might be both.

#### Multi-modal RAG: (6 points)

1. How do models like CLIP enable the embedding of both text and images into a shared vector space? What are the advantages and disadvantages of using a unified embedding space for cross-modal retrieval in RAG systems.
2. In systems like [Colpali](https://arxiv.org/pdf/2407.01449), how does dividing document images into patches enhance the retrieval process in multimodal RAG? Explore how patch-based processing preserves structural information and its impact on retrieval accuracy.
3. What are the implications of converting non-text modalities (e.g., images) into textual representations for retrieval purposes? Discuss the benefits and drawbacks of grounding all modalities into a primary modality, such as text, in the context of RAG.

**1.**

Models like CLIP (Contrastive Language–Image Pretraining) are designed to bridge the gap between text and images by embedding both into a shared vector space. This means that whether you input a photo of a dog or the sentence "a golden retriever playing fetch," CLIP can map them to nearby points in a high-dimensional space where their meanings align.  

The magic happens through a dual-encoder architecture—one neural network processes images (often a Vision Transformer or CNN), while another handles text (typically a Transformer). These networks are trained together on massive datasets of paired images and captions, using a contrastive learning objective. Essentially, the model learns to pull matching image-text pairs closer in the vector space while pushing unrelated pairs apart. For example, a picture of a sunset and its caption "vibrant sunset over the ocean" would end up with similar embeddings, while a mismatched pair like the same sunset image paired with "a busy city street" would be far apart.  

A key advantage of this shared space is its versatility in cross-modal retrieval, especially for Retrieval-Augmented Generation (RAG) systems. Imagine a search engine where you could type "waterfall in a tropical forest" and get relevant images, or upload a photo of a dish and retrieve recipes that match it—all because both modalities "speak the same language" in the embedding space. This eliminates the need for separate systems to handle text and images, streamlining infrastructure and enabling more intuitive multimodal interactions.  

However, the approach isn’t without challenges. Training CLIP effectively requires enormous datasets of high-quality image-text pairs, and the alignment between modalities isn’t always perfect. A painting of a cat might embed near the text "feline portrait," but subtle nuances—like the artist’s style or emotional tone—could be lost. There’s also a computational cost: running two encoders and comparing high-dimensional vectors demands significant resources. And while the shared space sacrifices some modality-specific specialization, the tradeoff is often worth it for applications needing flexible cross-modal understanding.  

In practice, CLIP-style embeddings have unlocked powerful use cases, from improving accessibility (e.g., generating alt text for images) to enhancing creative tools (like text-to-image search). But they’re not a silver bullet—designers must weigh the benefits of unified embeddings against their limitations, ensuring the system aligns with real-world needs. When done well, though, this technique brings us closer to AI that truly understands the connections between words and visuals.

**2.**

When dealing with document images in systems like Colpali, breaking them down into smaller patches before processing isn't just a technical detail—it fundamentally changes how well the system understands and retrieves information. Imagine trying to analyze a dense research paper or a business report all at once; you'd likely miss important details buried in the layout. That's exactly why patch-based processing makes such a difference in multimodal RAG systems.

By splitting documents into manageable patches—whether they're paragraphs, tables, diagrams, or captions—the system can examine each section with precision. This is especially valuable because documents aren't uniform; a single page might contain a sidebar with key statistics, an illustrative chart, and blocks of explanatory text. Patch-level analysis preserves this structural nuance, allowing the model to recognize that a query about "sales growth trends" should prioritize the line graph patch rather than the methodology paragraph nearby.

This granular approach solves several real-world problems. First, it prevents small but critical elements from getting drowned out when processing full pages—a footnote with crucial disclaimers or a finely printed data table won't be overlooked. Second, it maintains the spatial relationships between components, so the system understands that a caption belongs to its adjacent image or that a bulleted list organizes related concepts. When you later search for content, this means results can pinpoint exact relevant sections rather than vaguely matching entire documents.

The benefits extend to performance too. Since patches isolate content regions, noisy elements like watermarks or marginalia won't distort the representation of important content. The system also gains efficiency; instead of laboriously reprocessing whole documents for every query, it can selectively compare query-relevant patches, speeding up retrieval. In applications like legal document review or academic research, where precision matters, this patch-aware retrieval can mean the difference between surfacing the perfect reference or drowning in vaguely related results.

Of course, there are challenges—determining optimal patch sizes, handling overlapping content, and ensuring seamless reconstruction of the full document context. But when implemented well, as in Colpali's approach, patch-based processing transforms document images from blurry snapshots into searchable, semantically rich maps where every element has its place and purpose. This is why modern multimodal RAG systems increasingly adopt this strategy for handling real-world documents where layout carries as much meaning as the raw text itself.

**3.**

When building retrieval-augmented generation (RAG) systems that need to handle both text and images—or other non-text data like audio or video—one approach is to convert everything into text before retrieval. This might seem counterintuitive at first: why turn a rich image into a description when you could process it directly? But there are some compelling reasons this strategy works well in practice—along with some tradeoffs worth understanding.  

On the upside, using text as a common language simplifies everything. Retrieval systems have spent decades optimizing how to search through text efficiently, with tools like keyword matching, semantic search, and dense vector retrieval. By converting an image into a caption (e.g., "a red bicycle leaning against a brick wall"), you can leverage these battle-tested methods without reinventing the wheel. This unification also makes the system more interpretable: if a user searches for "bicycle photos" and gets a result, it’s easy to trace back that the match happened because the system stored the textual description "red bicycle." Storage becomes cheaper too—a few kilobytes of text replace megabytes of image data—and indexing scales more smoothly.  

Text also acts as a universal bridge. Imagine a system that needs to retrieve medical scans, satellite images, and podcast clips alongside research papers. Describing all of them in text (e.g., "MRI showing a torn meniscus," "aerial view of suburban sprawl," "interview about renewable energy policy") lets a single retrieval pipeline handle wildly different formats without needing custom architectures for each.  

But the drawbacks are real. Text is a lossy format for visuals. A painting described as "abstract blue and yellow shapes" loses the emotional impact of brushstrokes; a flowchart converted to text might miss the clarity of its arrows and spatial layout. These losses compound if the conversion step is weak—say, an image-captioning model misidentifies a dog as a wolf, or OCR garbles a critical number in a table. Even with perfect conversions, text struggles to capture subjective qualities like ambiance, artistic style, or the humor in a meme. Retrieval might surface technically correct but irrelevant results (e.g., matching "cat on a couch" to a cartoon when the user wanted real photos). There’s also added latency and cost from running separate models to generate descriptions upfront.  

So when does this approach make sense? If your use case prioritizes broad accessibility, simplicity, and integration with existing NLP tools—and if losing some visual nuance is acceptable—textual conversion is a pragmatic choice. But for applications where pixel-perfect accuracy or rich multimodal interaction matters (e.g., design platforms, medical imaging), hybrid systems that preserve native modalities often work better. The key is aligning the strategy with what users actually need to retrieve and why.

**LLM Usage:**
https://chatgpt.com/share/68267a5f-8b90-8010-94af-169c9f45ac6a